# Generated by Django 5.1 on 2026-01-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['position', 'created_at']},
        ),
        migrations.RemoveIndex(
            model_name='chat',
            name='conversatio_convers_dea17a_idx',
        ),
        migrations.AddField(
            model_name='chat',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['conversation', 'position'], name='conversatio_convers_0cb97f_idx'),
        ),
    ]
