# Generated by Django 5.1 on 2026-02-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_message_content_search_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='instructions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
