# Generated by Django 5.1 on 2026-02-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_add_chat_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_stopped',
            field=models.BooleanField(default=False),
        ),
    ]
