# Generated by Django 5.1 on 2025-11-27 10:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the room', max_length=255)),
                ('description', models.TextField(blank=True, help_text="Optional description of the room's purpose")),
                ('language', models.CharField(default='auto', help_text="Language code or 'auto' for auto-detection", max_length=10)),
                ('max_response_tokens', models.IntegerField(default=500, help_text='Maximum tokens per agent response')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceRoomAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(help_text="Name shown for this agent (e.g., 'The Skeptic', 'The Optimist')", max_length=100)),
                ('model_id', models.CharField(help_text="OpenRouter model ID (e.g., 'anthropic/claude-3-sonnet')", max_length=255)),
                ('system_prompt', models.TextField(help_text="System prompt defining the agent's persona and behavior")),
                ('voice_id', models.CharField(help_text='ElevenLabs voice ID', max_length=100)),
                ('voice_name', models.CharField(help_text='Display name for the voice', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Order in which this agent speaks (lower = earlier)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='voice_rooms.voiceroom')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceRoomSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('listening', 'Listening'), ('processing', 'Processing'), ('speaking', 'Speaking'), ('paused', 'Paused'), ('ended', 'Ended')], default='idle', max_length=20)),
                ('current_speaker', models.CharField(blank=True, help_text="ID of current speaker (agent_id or 'user')", max_length=100, null=True)),
                ('detected_language', models.CharField(blank=True, help_text='Detected language from user speech', max_length=10, null=True)),
                ('total_duration_ms', models.IntegerField(default=0, help_text='Total session duration in milliseconds')),
                ('total_user_speaking_ms', models.IntegerField(default=0, help_text='Total user speaking time in milliseconds')),
                ('total_agent_speaking_ms', models.IntegerField(default=0, help_text='Total agent speaking time in milliseconds')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='voice_rooms.voiceroom')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceRoomMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField(help_text='Text content of the message')),
                ('audio_duration_ms', models.IntegerField(blank=True, help_text='Duration of the audio in milliseconds', null=True)),
                ('stt_latency_ms', models.IntegerField(blank=True, help_text='Speech-to-text processing latency', null=True)),
                ('llm_latency_ms', models.IntegerField(blank=True, help_text='LLM response generation latency', null=True)),
                ('tts_latency_ms', models.IntegerField(blank=True, help_text='Text-to-speech processing latency', null=True)),
                ('model_id', models.CharField(blank=True, help_text='OpenRouter model ID used', max_length=255, null=True)),
                ('prompt_tokens', models.IntegerField(blank=True, help_text='Number of prompt tokens', null=True)),
                ('completion_tokens', models.IntegerField(blank=True, help_text='Number of completion tokens', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, help_text='Agent that sent this message (null for user messages)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='voice_rooms.voiceroomagent')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='voice_rooms.voiceroomsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='voiceroom',
            index=models.Index(fields=['user', '-updated_at'], name='voice_rooms_user_id_7493ab_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceroom',
            index=models.Index(fields=['is_active'], name='voice_rooms_is_acti_e89327_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceroomagent',
            index=models.Index(fields=['room', 'order'], name='voice_rooms_room_id_aaf67d_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceroomagent',
            index=models.Index(fields=['is_active'], name='voice_rooms_is_acti_5cc6bb_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceroomsession',
            index=models.Index(fields=['room', '-started_at'], name='voice_rooms_room_id_6c4b58_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceroomsession',
            index=models.Index(fields=['status'], name='voice_rooms_status_11e814_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceroommessage',
            index=models.Index(fields=['session', 'created_at'], name='voice_rooms_session_06a7e6_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceroommessage',
            index=models.Index(fields=['role'], name='voice_rooms_role_f9fcf1_idx'),
        ),
    ]
