# Generated by Django 5.1 on 2025-11-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceroomagent',
            name='voice_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Voice settings: stability, similarity_boost, style, use_speaker_boost, speed'),
        ),
    ]
