# Generated by Django 5.1 on 2025-12-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_rooms', '0002_add_voice_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceroom',
            name='user_name',
            field=models.CharField(blank=True, help_text="User's display name for agents to address them", max_length=100),
        ),
    ]
