# Generated by Django 5.1 on 2026-01-28 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0003_remove_branch_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('framework', models.CharField(choices=[('react', 'React'), ('html', 'HTML'), ('svg', 'SVG')], default='react', max_length=20)),
                ('storage_type', models.CharField(choices=[('inline', 'Inline'), ('r2', 'R2')], default='inline', max_length=20)),
                ('code', models.TextField(blank=True)),
                ('r2_bucket', models.CharField(blank=True, max_length=255)),
                ('r2_key', models.CharField(blank=True, max_length=500)),
                ('dependencies', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('preview_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sparks', to='conversations.chat')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sparks', to='conversations.message')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='sparks.spark')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sparks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='sparks_spar_user_id_8b7106_idx'), models.Index(fields=['user', 'created_at'], name='sparks_spar_user_id_dc947b_idx'), models.Index(fields=['chat'], name='sparks_spar_chat_id_23588d_idx'), models.Index(fields=['message'], name='sparks_spar_message_d726e5_idx')],
            },
        ),
    ]
