# Generated by Django 5.1 on 2026-02-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparks', '0001_initial'),
        ('workspaces', '0006_add_assets_to_spark'),
    ]

    operations = [
        migrations.AddField(
            model_name='spark',
            name='assets',
            field=models.ManyToManyField(blank=True, help_text='Images/videos referenced by this spark', related_name='sparks', to='workspaces.asset'),
        ),
    ]
