# Generated by Django 5.1 on 2026-02-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparks', '0006_remove_scaffolding_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sparkdeployment',
            new_name='sparks_spar_spark_i_8499cb_idx',
            old_name='sparks_spark_spark_i_idx',
        ),
        migrations.RenameIndex(
            model_name='sparkdeployment',
            new_name='sparks_spar_user_id_8350fe_idx',
            old_name='sparks_spark_user_id_idx',
        ),
        migrations.AddField(
            model_name='spark',
            name='is_ignited',
            field=models.BooleanField(default=False),
        ),
    ]
