# Generated by Django 5.1 on 2026-02-21 13:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_message_is_stopped'),
        ('sparks', '0007_spark_is_ignited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('project_path', models.CharField(max_length=500)),
                ('preview_command', models.CharField(default='npm run dev', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apps', to='conversations.chat')),
                ('spark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='sparks.spark')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='sparks_app_user_id_fcbf57_idx'), models.Index(fields=['spark', '-created_at'], name='sparks_app_spark_i_ad271b_idx'), models.Index(fields=['chat'], name='sparks_app_chat_id_eee293_idx')],
                'constraints': [models.UniqueConstraint(fields=('spark', 'version'), name='unique_app_version_per_spark')],
            },
        ),
    ]
