"""
Scout Agent

A lightweight agent using a cheap model to explore the codebase and gather
information needed for code modifications. Produces structured findings
that the editor agent can use efficiently.
"""

import json
import logging
import re
import uuid
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from .compressor import compress_tool_result
from .constants import (
    SCOUT_MAX_ITERATIONS,
    SCOUT_MAX_TOKENS,
    SCOUT_MODEL_ID,
    SCOUT_SYSTEM_PROMPT,
    SCOUT_TOOLS,
    MAX_SNIPPET_CHARS,
    MAX_SNIPPETS_FOR_EDITOR,
)

logger = logging.getLogger(__name__)


@dataclass
class FileToModify:
    """A file that needs to be modified."""
    path: str
    reason: str
    relevant_lines: Optional[str] = None  # e.g., "50-80"


@dataclass
class FileToCreate:
    """A new file to be created."""
    path: str
    purpose: str


@dataclass
class CodeSnippet:
    """A relevant code snippet."""
    path: str
    lines: str  # e.g., "10-30"
    content: str


@dataclass
class ScoutReport:
    """Report generated by the scout agent."""
    files_to_modify: List[FileToModify] = field(default_factory=list)
    files_to_create: List[FileToCreate] = field(default_factory=list)
    approach: str = ""
    snippets: List[CodeSnippet] = field(default_factory=list)
    exploration_tokens: int = 0
    exploration_cost: float = 0.0
    iterations: int = 0
    success: bool = True
    error: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "files_to_modify": [
                {"path": f.path, "reason": f.reason, "lines": f.relevant_lines}
                for f in self.files_to_modify
            ],
            "files_to_create": [
                {"path": f.path, "purpose": f.purpose}
                for f in self.files_to_create
            ],
            "approach": self.approach,
            "snippets": [
                {"path": s.path, "lines": s.lines, "content": s.content[:MAX_SNIPPET_CHARS]}
                for s in self.snippets[:MAX_SNIPPETS_FOR_EDITOR]
            ],
            "exploration_tokens": self.exploration_tokens,
            "exploration_cost": self.exploration_cost,
            "iterations": self.iterations,
            "success": self.success,
            "error": self.error,
        }

    @classmethod
    def from_json(cls, json_str: str) -> "ScoutReport":
        """Parse scout report from JSON string."""
        try:
            data = json.loads(json_str)

            files_to_modify = [
                FileToModify(
                    path=f.get("path", ""),
                    reason=f.get("reason", ""),
                    relevant_lines=f.get("lines"),
                )
                for f in data.get("files_to_modify", [])
            ]

            files_to_create = [
                FileToCreate(
                    path=f.get("path", ""),
                    purpose=f.get("purpose", ""),
                )
                for f in data.get("files_to_create", [])
            ]

            snippets = [
                CodeSnippet(
                    path=s.get("path", ""),
                    lines=s.get("lines", ""),
                    content=s.get("content", ""),
                )
                for s in data.get("snippets", [])
            ]

            return cls(
                files_to_modify=files_to_modify,
                files_to_create=files_to_create,
                approach=data.get("approach", ""),
                snippets=snippets,
            )

        except (json.JSONDecodeError, KeyError) as e:
            logger.warning(f"Failed to parse scout report JSON: {e}")
            return cls(success=False, error=f"Failed to parse report: {e}")


class ScoutAgent:
    """
    Lightweight agent for codebase exploration.

    Uses a cheap model (e.g., Haiku) to:
    1. Understand the task
    2. Explore relevant files
    3. Extract code snippets
    4. Produce a structured report for the editor
    """

    def __init__(self, model_id: Optional[str] = None, user=None):
        """
        Initialize scout agent.

        Args:
            model_id: Model to use (defaults to SCOUT_MODEL_ID)
            user: User instance for API key resolution
        """
        self.model_id = model_id or SCOUT_MODEL_ID
        self.user = user
        self._client = None

    @property
    def client(self):
        """Lazy-load the OpenRouter client."""
        if self._client is None:
            from llm.client import OpenRouterClient
            self._client = OpenRouterClient(user=self.user, request_source='scout')
        return self._client

    def explore(
        self,
        task: str,
        workspace_path: str,
        auth_token: str,
        user_id: str,
        session_id: str,
        on_step: Optional[callable] = None,
    ) -> ScoutReport:
        """
        Explore the codebase for a given task.

        Args:
            task: The coding task description
            workspace_path: Path to workspace (e.g., /workspace/chat-xxx/repo)
            auth_token: JWT token for tool execution
            user_id: User ID for tool execution
            session_id: Session ID for tool execution
            on_step: Optional callback for progress updates

        Returns:
            ScoutReport with exploration findings
        """
        logger.info("[Scout] === STARTING EXPLORATION ===")
        logger.info(f"[Scout] Task: {task[:200]}...")
        logger.info(f"[Scout] Workspace: {workspace_path}")
        logger.info(f"[Scout] Model: {self.model_id}")
        logger.info(f"[Scout] Max iterations: {SCOUT_MAX_ITERATIONS}")

        # Get scout tools (read-only subset)
        tools = self._get_scout_tools()
        logger.info(f"[Scout] Available tools: {[t['function']['name'] for t in tools]}")

        # Build initial messages
        messages = [
            {"role": "system", "content": SCOUT_SYSTEM_PROMPT},
            {"role": "user", "content": f"Task: {task}\n\nWorkspace: {workspace_path}"},
        ]

        total_prompt_tokens = 0
        total_completion_tokens = 0
        total_cost = 0.0
        iteration = 0

        # Loop detection - track file reads to prevent infinite loops
        file_read_counts: dict[str, int] = {}
        MAX_READS_PER_FILE = 2

        try:
            while iteration < SCOUT_MAX_ITERATIONS:
                iteration += 1
                logger.info(f"[Scout] --- Iteration {iteration}/{SCOUT_MAX_ITERATIONS} ---")

                if on_step:
                    on_step(f"Exploring codebase... (step {iteration})")

                # Call LLM
                logger.debug(f"[Scout] Calling LLM with {len(messages)} messages")
                result = self.client.complete(
                    model=self.model_id,
                    messages=messages,
                    max_tokens=SCOUT_MAX_TOKENS,
                    tools=tools,
                    tool_choice="auto",
                )

                # Track usage
                usage = result.get("usage", {})
                iter_prompt = usage.get("prompt_tokens", 0)
                iter_completion = usage.get("completion_tokens", 0)
                total_prompt_tokens += iter_prompt
                total_completion_tokens += iter_completion
                total_cost += float(result.get("cost", 0) or 0)

                logger.info(f"[Scout] LLM response: {iter_prompt} prompt + {iter_completion} completion tokens")

                content = result.get("content", "")
                tool_calls = result.get("tool_calls", [])

                if content:
                    logger.info(f"[Scout] Content: {content[:200]}...")

                # Check if scout is done (produced JSON report)
                if content and not tool_calls:
                    # Try to extract JSON report from content
                    report = self._extract_report(content)
                    if report:
                        report.exploration_tokens = total_prompt_tokens + total_completion_tokens
                        report.exploration_cost = total_cost
                        report.iterations = iteration
                        logger.info(
                            f"Scout completed in {iteration} iterations, "
                            f"found {len(report.files_to_modify)} files to modify"
                        )
                        return report

                # No tool calls and no report = done exploring
                if not tool_calls:
                    logger.info("[Scout] No tool calls, exploration complete")
                    break

                # Log tool calls
                logger.info(f"[Scout] Executing {len(tool_calls)} tool calls:")
                for tc in tool_calls:
                    tool_name = tc.get("function", {}).get("name", "unknown")
                    args = tc.get("function", {}).get("arguments", "{}")
                    logger.info(f"[Scout]   - {tool_name}: {args[:100]}...")

                # Execute tool calls with loop detection
                tool_results = self._execute_tools(
                    tool_calls=tool_calls,
                    auth_token=auth_token,
                    user_id=user_id,
                    session_id=session_id,
                    file_read_counts=file_read_counts,
                    max_reads_per_file=MAX_READS_PER_FILE,
                )

                logger.info(f"[Scout] Tool execution completed, {len(tool_results)} results")

                # Add assistant message with tool calls
                messages.append({
                    "role": "assistant",
                    "content": content or "",
                    "tool_calls": tool_calls,
                })

                # Add tool results
                for tool_result in tool_results:
                    messages.append(tool_result)

            # Max iterations reached, try to build report from exploration
            logger.warning(f"Scout reached max iterations ({SCOUT_MAX_ITERATIONS})")

            return ScoutReport(
                approach="Exploration incomplete - max iterations reached",
                exploration_tokens=total_prompt_tokens + total_completion_tokens,
                exploration_cost=total_cost,
                iterations=iteration,
                success=False,
                error="Max iterations reached",
            )

        except Exception as e:
            logger.exception(f"Scout exploration failed: {e}")
            return ScoutReport(
                exploration_tokens=total_prompt_tokens + total_completion_tokens,
                exploration_cost=total_cost,
                iterations=iteration,
                success=False,
                error=str(e),
            )

    def _get_scout_tools(self) -> List[Dict[str, Any]]:
        """Get tool definitions for scout (read-only subset)."""
        from sandbox.orchestrator.file_tools import FILE_TOOLS

        scout_tools = []
        for tool in FILE_TOOLS:
            tool_name = tool.get("function", {}).get("name", "")
            if tool_name in SCOUT_TOOLS:
                # Modify run_bash to be read-only
                if tool_name == "run_bash":
                    tool = dict(tool)
                    tool["function"] = dict(tool["function"])
                    tool["function"]["description"] = (
                        "Execute read-only bash commands for exploration. "
                        "Use for: grep, find, cat, head, tail, wc. "
                        "DO NOT modify files or run write operations."
                    )
                scout_tools.append(tool)

        return scout_tools

    def _execute_tools(
        self,
        tool_calls: List[Dict[str, Any]],
        auth_token: str,
        user_id: str,
        session_id: str,
        file_read_counts: Optional[Dict[str, int]] = None,
        max_reads_per_file: int = 2,
    ) -> List[Dict[str, Any]]:
        """Execute tool calls and return results."""
        from llm.file_tools_integration import handle_file_tool_calls

        if file_read_counts is None:
            file_read_counts = {}

        # Filter to scout tools only and apply loop detection
        scout_tool_calls = []
        loop_blocked = []  # (index, tc, blocked_result)

        for tc in tool_calls:
            tool_name = tc.get("function", {}).get("name", "")
            if tool_name not in SCOUT_TOOLS:
                logger.warning(f"Scout tried to use non-scout tool: {tool_name}")
                continue

            # Ensure tool call has ID
            if not tc.get("id"):
                tc["id"] = f"tool_{tool_name}_{uuid.uuid4().hex[:16]}"

            # Loop detection for read_file
            if tool_name == "read_file":
                try:
                    args = json.loads(tc.get("function", {}).get("arguments", "{}"))
                    path = args.get("path", "")
                    file_read_counts[path] = file_read_counts.get(path, 0) + 1

                    if file_read_counts[path] > max_reads_per_file:
                        logger.warning(f"[Scout] Loop detected: {path} read {file_read_counts[path]} times")
                        loop_blocked.append((len(scout_tool_calls) + len(loop_blocked), tc, {
                            "role": "tool",
                            "tool_call_id": tc.get("id"),
                            "content": json.dumps({
                                "success": False,
                                "error": f"LOOP DETECTED: Already read '{path}' {max_reads_per_file} times. "
                                         "Stop re-reading and produce your final report NOW."
                            })
                        }))
                        continue
                except json.JSONDecodeError:
                    pass

            scout_tool_calls.append(tc)

        if not scout_tool_calls and not loop_blocked:
            return []

        # Execute non-blocked tools
        if scout_tool_calls:
            results = handle_file_tool_calls(
                tool_calls=scout_tool_calls,
                user_id=user_id,
                conversation_id=session_id,
                chat_id=session_id,
                sync_mode=True,
                auth_token=auth_token,
            )
        else:
            results = []

        # Merge results with blocked results in correct order
        if loop_blocked:
            final_results = []
            results_iter = iter(results)
            blocked_iter = iter(loop_blocked)
            next_blocked = next(blocked_iter, None)

            for i in range(len(scout_tool_calls) + len(loop_blocked)):
                if next_blocked and next_blocked[0] == i:
                    final_results.append(next_blocked[2])
                    next_blocked = next(blocked_iter, None)
                else:
                    final_results.append(next(results_iter))
            results = final_results

        # Compress results to save tokens (skip already-blocked ones)
        compressed_results = []
        all_tool_calls = {tc.get("id"): tc for tc in tool_calls}

        for result in results:
            tool_call_id = result.get("tool_call_id")
            tc = all_tool_calls.get(tool_call_id, {})
            tool_name = tc.get("function", {}).get("name", "")
            args = {}
            try:
                args = json.loads(tc.get("function", {}).get("arguments", "{}"))
            except json.JSONDecodeError:
                pass

            # Don't compress blocked results (they're already minimal)
            content = result.get("content", "")
            if "LOOP DETECTED" not in content:
                content = compress_tool_result(tool_name, content, args)

            compressed_results.append({
                "role": "tool",
                "tool_call_id": tool_call_id,
                "content": content,
            })

        return compressed_results

    def _extract_report(self, content: str) -> Optional[ScoutReport]:
        """Extract ScoutReport from LLM response content."""
        # Try to find JSON in the content
        json_patterns = [
            r'```json\s*([\s\S]*?)\s*```',  # ```json ... ```
            r'```\s*([\s\S]*?)\s*```',       # ``` ... ```
            r'\{[\s\S]*"files_to_modify"[\s\S]*\}',  # Raw JSON with expected field
        ]

        for pattern in json_patterns:
            match = re.search(pattern, content)
            if match:
                json_str = match.group(1) if match.lastindex else match.group(0)
                report = ScoutReport.from_json(json_str)
                if report.success or report.files_to_modify or report.approach:
                    return report

        # Try parsing entire content as JSON
        try:
            report = ScoutReport.from_json(content)
            if report.success or report.files_to_modify or report.approach:
                return report
        except Exception:
            pass

        # Extract approach from natural language if no JSON
        if "approach" in content.lower() or "plan" in content.lower():
            # Use the content as the approach
            return ScoutReport(
                approach=content[:2000],
                success=True,
            )

        return None


def create_scout(model_id: Optional[str] = None, user=None) -> ScoutAgent:
    """Create a new scout agent instance."""
    return ScoutAgent(model_id=model_id, user=user)
