"""
Parser for extracting spark definitions from LLM responses.

Sparks are interactive React components generated by AI.
This module supports two formats:
1. New format: Fenced code blocks with `tsx spark:Title` or `html spark:Title`
2. Legacy format: <spark title="...">code</spark> tags

This module extracts spark definitions and handles both creation and update operations.
"""
import re
import logging
from typing import List, Optional, Set
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)

# New fenced code block format: ```tsx spark:Title\ncode\n```
SPARK_FENCED_PATTERN = re.compile(
    r'```(tsx|jsx|html|svg)\s+spark:([^\n]+)\n(.*?)```',
    re.DOTALL | re.IGNORECASE
)

# Legacy pattern for spark creation tags
SPARK_CREATE_PATTERN = re.compile(
    r'<spark\s+title="([^"]+)"(?:\s+framework="([^"]+)")?\s*>\s*(.*?)\s*</spark>',
    re.DOTALL | re.IGNORECASE
)

SPARK_UPDATE_PATTERN = re.compile(
    r'<spark-update\s+id="([^"]+)">\s*(.*?)\s*</spark-update>',
    re.DOTALL | re.IGNORECASE
)

# Pattern to detect markdown code fences (for cleaning legacy format)
CODE_FENCE_PATTERN = re.compile(r'^```(?:tsx?|jsx?|javascript|react)?\s*\n?', re.MULTILINE)
CODE_FENCE_END_PATTERN = re.compile(r'\n?```\s*$', re.MULTILINE)


@dataclass
class SparkDefinition:
    """Parsed spark from LLM response."""
    operation: str  # 'create' or 'update'
    title: Optional[str] = None
    framework: str = 'react'
    code: Optional[str] = None
    spark_id: Optional[str] = None
    update_instructions: Optional[str] = None
    dependencies: List[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            'operation': self.operation,
            'title': self.title,
            'framework': self.framework,
            'code': self.code,
            'spark_id': self.spark_id,
            'update_instructions': self.update_instructions,
            'dependencies': self.dependencies,
        }


def _language_to_framework(lang: str) -> str:
    """Map language identifier to framework."""
    lang_lower = lang.lower()
    if lang_lower in ('tsx', 'jsx'):
        return 'react'
    if lang_lower == 'svg':
        return 'svg'
    return 'html'


def extract_sparks(content: str) -> List[SparkDefinition]:
    """
    Extract spark definitions from assistant response content.
    Supports both new fenced code block format and legacy <spark> tags.

    Args:
        content: The raw text content from the LLM response

    Returns:
        List of SparkDefinition objects
    """
    sparks = []
    seen_codes: Set[str] = set()

    # First, extract from new fenced code block format: ```tsx spark:Title
    for match in SPARK_FENCED_PATTERN.finditer(content):
        language = match.group(1).strip()
        title = match.group(2).strip()
        code = match.group(3).strip()

        # Avoid duplicates (use first 100 chars as hash)
        code_hash = code[:100]
        if code_hash in seen_codes:
            continue
        seen_codes.add(code_hash)

        framework = _language_to_framework(language)
        dependencies = detect_spark_dependencies(code)

        sparks.append(SparkDefinition(
            operation='create',
            title=title,
            framework=framework,
            code=code,
            dependencies=dependencies,
        ))
        logger.info(f"Extracted spark (fenced): {title} ({len(code)} chars, deps: {dependencies})")

    # Then, extract from legacy spark creation tags
    for match in SPARK_CREATE_PATTERN.finditer(content):
        title = match.group(1).strip()
        framework = (match.group(2) or 'react').strip().lower()
        code = match.group(3).strip()

        # Clean up code (remove markdown code fences if present)
        code = clean_spark_code(code)

        # Avoid duplicates
        code_hash = code[:100]
        if code_hash in seen_codes:
            continue
        seen_codes.add(code_hash)

        dependencies = detect_spark_dependencies(code)

        sparks.append(SparkDefinition(
            operation='create',
            title=title,
            framework=framework,
            code=code,
            dependencies=dependencies,
        ))
        logger.info(f"Extracted spark (legacy): {title} ({len(code)} chars, deps: {dependencies})")

    # Extract spark updates
    for match in SPARK_UPDATE_PATTERN.finditer(content):
        spark_id = match.group(1).strip()
        instructions = match.group(2).strip()

        sparks.append(SparkDefinition(
            operation='update',
            spark_id=spark_id,
            update_instructions=instructions,
        ))
        logger.info(f"Extracted spark update for: {spark_id}")

    return sparks


def clean_spark_code(code: str) -> str:
    """
    Clean up spark code by removing markdown artifacts.

    Args:
        code: Raw code from spark tag

    Returns:
        Cleaned code string
    """
    # Remove leading/trailing markdown code fences
    code = CODE_FENCE_PATTERN.sub('', code)
    code = CODE_FENCE_END_PATTERN.sub('', code)

    # Normalize line endings
    code = code.replace('\r\n', '\n')

    return code.strip()


def remove_spark_tags(content: str) -> str:
    """
    Remove spark tags from content, leaving only placeholder text.
    Note: Fenced spark blocks are NOT removed since the code is copy-pastable.

    Args:
        content: Content with spark tags

    Returns:
        Content with legacy spark tags replaced by placeholders
    """
    # Remove legacy spark creation tags (keep a placeholder)
    content = SPARK_CREATE_PATTERN.sub(
        lambda m: f'\n[Created Spark: {m.group(1)}]\n',
        content
    )

    # Remove spark update tags
    content = SPARK_UPDATE_PATTERN.sub(
        lambda m: f'\n[Updating Spark: {m.group(1)}]\n',
        content
    )

    return content.strip()


def _extract_package_name(specifier: str) -> str:
    """
    Extract the npm package name from a bare specifier.
    Handles scoped packages: '@tanstack/react-query/foo' → '@tanstack/react-query'
    Handles subpaths: 'recharts/es6/chart' → 'recharts'
    """
    if specifier.startswith('@'):
        parts = specifier.split('/')
        return f'{parts[0]}/{parts[1]}' if len(parts) >= 2 else specifier
    return specifier.split('/')[0]


# Regex to parse ES import statements. Best-effort — may match imports inside
# multiline strings, template literals, or comments. This is acceptable since
# dependencies is informational (used for ignite/display), not for security.
_IMPORT_PATTERN = re.compile(
    r'''import\s+(?:(?:\{[^}]*\}|[\w*]+(?:\s*,\s*\{[^}]*\})?|\*\s+as\s+[\w]+)\s+from\s+)?['"]([^'"]+)['"]'''
)


def detect_spark_dependencies(code: str) -> List[str]:
    """
    Detect which libraries a spark uses based on code analysis.
    Parses both ES import statements and global-pattern usage.

    Args:
        code: Spark code

    Returns:
        List of dependency names
    """
    dependencies: Set[str] = set()

    # Parse ES import statements
    for match in _IMPORT_PATTERN.finditer(code):
        specifier = match.group(1)
        # Skip relative paths, URLs, and CSS imports
        if specifier.startswith('.') or '://' in specifier or specifier.endswith('.css'):
            continue
        base = _extract_package_name(specifier)
        # Skip react/react-dom (always available, not a "dependency")
        if base not in ('react', 'react-dom'):
            dependencies.add(base)

    # Check for Recharts usage via globals (backward compat)
    recharts_patterns = [
        r'Recharts\.',
        r'\b(LineChart|BarChart|PieChart|AreaChart|RadarChart|ComposedChart)\b',
        r'\b(XAxis|YAxis|Tooltip|Legend|Line|Bar|Pie|Area|Cell|ResponsiveContainer)\b',
    ]
    for pattern in recharts_patterns:
        if re.search(pattern, code):
            dependencies.add('recharts')
            break

    # Check for Lucide icons via globals
    lucide_patterns = [
        r'lucideReact\.',
        r'\bLucide\w+\b',
    ]
    for pattern in lucide_patterns:
        if re.search(pattern, code):
            dependencies.add('lucide-react')
            break

    # Check for D3 via globals
    if re.search(r'\bd3\.', code):
        dependencies.add('d3')

    # Check for Three.js via globals
    if re.search(r'\bTHREE\.', code):
        dependencies.add('three')

    return sorted(dependencies)


def has_spark_tags(content: str) -> bool:
    """
    Check if content contains any spark tags or spark code blocks.

    Args:
        content: Content to check

    Returns:
        True if spark tags or blocks found
    """
    return bool(
        SPARK_FENCED_PATTERN.search(content) or
        SPARK_CREATE_PATTERN.search(content) or
        SPARK_UPDATE_PATTERN.search(content)
    )


def get_spark_placeholder(title: str, spark_id: str) -> str:
    """
    Generate a placeholder for a spark that will be replaced by the frontend.

    Args:
        title: Spark title
        spark_id: UUID of the created spark

    Returns:
        Placeholder string
    """
    return f'<spark-ref id="{spark_id}" title="{title}" />'
