"""
Spark models for storing interactive React components generated by AI.

Sparks are self-contained React components that render live in the chat interface.
They support versioning, R2 storage for large components, and can be shared/exported.
"""
import uuid
from django.db import models
from django.conf import settings
from conversations.models import Chat, Message
from workspaces.models import Asset


class Spark(models.Model):
    """
    Interactive React component generated by AI.

    Sparks can be stored inline (for small components) or in R2 (for larger ones).
    Updates create new versions linked via parent reference.
    """

    class Framework(models.TextChoices):
        REACT = 'react', 'React'
        HTML = 'html', 'HTML'
        SVG = 'svg', 'SVG'
        MARKDOWN = 'markdown', 'Markdown'
        MERMAID = 'mermaid', 'Mermaid'
        PDF = 'pdf', 'PDF'
        DOCX = 'docx', 'DOCX'
        ICS = 'ics', 'ICS'
        CSV = 'csv', 'CSV'
        XLSX = 'xlsx', 'Excel Spreadsheet'

    # Framework classification helpers
    RENDERABLE_FRAMEWORKS = {'react', 'html', 'svg', 'markdown', 'mermaid'}
    DIRECT_DOWNLOAD_FRAMEWORKS = {'csv', 'ics'}
    GENERATED_DOCUMENT_FRAMEWORKS = {'pdf', 'docx', 'xlsx'}

    MIME_TYPES = {
        'pdf': 'application/pdf',
        'docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'ics': 'text/calendar',
        'csv': 'text/csv',
    }

    FILE_EXTENSIONS = {
        'pdf': '.pdf',
        'docx': '.docx',
        'xlsx': '.xlsx',
        'ics': '.ics',
        'csv': '.csv',
    }

    class StorageType(models.TextChoices):
        INLINE = 'inline', 'Inline'
        R2 = 'r2', 'R2'

    # Primary key
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    # Owner
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='sparks'
    )

    # Optional associations
    chat = models.ForeignKey(
        Chat,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='sparks'
    )
    message = models.ForeignKey(
        Message,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='sparks'
    )

    # Metadata
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    framework = models.CharField(
        max_length=20,
        choices=Framework.choices,
        default=Framework.REACT
    )

    # Code storage
    storage_type = models.CharField(
        max_length=20,
        choices=StorageType.choices,
        default=StorageType.INLINE
    )
    code = models.TextField(blank=True)  # For inline storage
    r2_bucket = models.CharField(max_length=255, blank=True)
    r2_key = models.CharField(max_length=500, blank=True)

    # Dependencies detected from code
    dependencies = models.JSONField(default=list, blank=True)
    # e.g., ['recharts', 'lucide-react']

    # Versioning
    version = models.PositiveIntegerField(default=1)
    parent = models.ForeignKey(
        'self',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='versions'
    )

    # Preview thumbnail URL (generated on save)
    preview_url = models.URLField(blank=True)

    # R2 key for generated binary output (PDF/DOCX)
    generated_r2_key = models.CharField(
        max_length=500, blank=True, default='',
        help_text='R2 key for generated binary output (PDF/DOCX)'
    )

    # Referenced assets (images, videos) that this spark uses
    # These are made available to the spark via window.__SPARK_ASSETS__
    assets = models.ManyToManyField(
        Asset,
        blank=True,
        related_name='sparks',
        help_text='Images/videos referenced by this spark'
    )

    # Whether the spark has been ignited (scaffolded into a full project)
    is_ignited = models.BooleanField(default=False)

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated_at']
        indexes = [
            models.Index(fields=['user', '-updated_at']),
            models.Index(fields=['user', 'created_at']),
            models.Index(fields=['chat']),
            models.Index(fields=['message']),
        ]

    def __str__(self):
        return f"{self.title} (v{self.version})"

    def get_code(self):
        """Get the spark code, fetching from R2 if needed."""
        if self.storage_type == self.StorageType.INLINE:
            return self.code

        # Fetch from R2
        from workspaces.services.workspace_storage import WorkspaceStorageService
        storage = WorkspaceStorageService()
        content = storage.retrieve_file(self.r2_key)
        return content.decode('utf-8') if content else ''

    def save_code(self, code: str):
        """Save code, choosing storage type based on size."""
        threshold = getattr(settings, 'SPARK_INLINE_THRESHOLD', 256 * 1024)  # 256KB

        if len(code) <= threshold:
            self.storage_type = self.StorageType.INLINE
            self.code = code
            self.r2_bucket = ''
            self.r2_key = ''
        else:
            self._upload_to_r2(code)

    def is_renderable(self):
        """True for types rendered in-browser (react/html/svg/markdown/mermaid)."""
        return self.framework in self.RENDERABLE_FRAMEWORKS

    def is_direct_download(self):
        """True for text content served as downloadable files (csv/ics)."""
        return self.framework in self.DIRECT_DOWNLOAD_FRAMEWORKS

    def is_generated_document(self):
        """True for types that need Python executor to produce binary output (pdf/docx)."""
        return self.framework in self.GENERATED_DOCUMENT_FRAMEWORKS

    def get_mime_type(self):
        """Get MIME type for downloadable frameworks."""
        return self.MIME_TYPES.get(self.framework)

    def get_file_extension(self):
        """Get file extension for downloadable frameworks."""
        return self.FILE_EXTENSIONS.get(self.framework)

    def get_sanitized_filename(self):
        """Get a sanitized filename from the title + extension."""
        import re
        name = re.sub(r'[^\w\s-]', '', self.title).strip()
        name = re.sub(r'\s+', '-', name)[:100]
        ext = self.get_file_extension() or ''
        return f"{name}{ext}" if name else f"spark{ext}"

    def _upload_to_r2(self, code: str):
        """Upload code to R2 storage."""
        from workspaces.services.workspace_storage import WorkspaceStorageService

        storage = WorkspaceStorageService()
        if self.chat_id:
            r2_key = f"{self.user_id}/chats/{self.chat_id}/sparks/{self.id}/code.tsx"
        else:
            r2_key = f"{self.user_id}/sparks/{self.id}/code.tsx"

        storage.store_file(
            content=code.encode('utf-8'),
            r2_key=r2_key,
            mime_type='text/typescript',
        )

        self.storage_type = self.StorageType.R2
        self.code = ''  # Clear inline code
        self.r2_bucket = storage.bucket_name
        self.r2_key = r2_key


class SparkDeployment(models.Model):
    """
    Tracks deployment of a Spark as a standalone Next.js app to Vercel.

    Created when a user clicks "Ignite" or asks the LLM to deploy a spark.
    The coding agent scaffolds a Next.js project, builds it, and deploys
    to Vercel via the Claimable Deploy API.
    """

    class Status(models.TextChoices):
        PENDING = 'pending', 'Pending'
        DEPLOYING = 'deploying', 'Deploying'
        DEPLOYED = 'deployed', 'Deployed'
        FAILED = 'failed', 'Failed'

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    spark = models.ForeignKey(
        Spark,
        on_delete=models.CASCADE,
        related_name='deployments'
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='spark_deployments'
    )
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.PENDING
    )
    preview_url = models.URLField(blank=True)
    claim_url = models.URLField(blank=True)
    deployment_id = models.CharField(max_length=255, blank=True)
    project_id = models.CharField(max_length=255, blank=True)
    error_message = models.TextField(blank=True)
    coding_agent_job_id = models.CharField(max_length=255, blank=True)
    cost_usd = models.DecimalField(max_digits=10, decimal_places=6, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['spark', '-created_at']),
            models.Index(fields=['user', 'status']),
        ]

    def __str__(self):
        return f"Deployment {self.id} ({self.status}) for {self.spark.title}"


class App(models.Model):
    """Persisted application created from an ignited Spark."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    spark = models.ForeignKey(Spark, on_delete=models.CASCADE, related_name='apps')
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='apps',
    )
    chat = models.ForeignKey(
        Chat,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='apps',
    )
    title = models.CharField(max_length=255)
    version = models.PositiveIntegerField(default=1)
    project_path = models.CharField(max_length=500)
    preview_command = models.CharField(max_length=1000, default='npm run dev')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['user', '-created_at']),
            models.Index(fields=['spark', '-created_at']),
            models.Index(fields=['chat']),
        ]
        constraints = [
            models.UniqueConstraint(
                fields=['spark', 'version'],
                name='unique_app_version_per_spark',
            )
        ]

    def __str__(self):
        return f"{self.title} v{self.version}"
