"""Normalization applied to a captured SSE transcript before comparison.

A golden transcript is compared byte for byte. Only values that a replay
of the same scenario cannot reproduce are rewritten, and every rewrite is
declared as an explicit rule in `NORMALIZATION_RULES`. Everything else --
event order, event names, field names, field order inside each JSON
payload, chunk boundaries, and the SSE framing (``event: <name>\\n``,
``data: <json>\\n``, terminating blank line) -- is compared verbatim, so a
reordered event, a renamed field, or a dropped chunk fails the test.

Preconditions the fixtures uphold:

* Every identifier a fixture supplies -- generation ids, tool call ids,
  model ids, workspace paths -- is written in a shape that no rule
  matches. An RFC-4122 UUID in a transcript is therefore always one the
  code under test produced (a database primary key, or the ``uuid4``
  fallback for a tool call that arrived without an id).
* Token counts and prices come from fixtures and a seeded catalog row, so
  usage and cost figures are reproducible and stay unnormalized: a cost
  drift is a behavior change and must fail.
"""

import re
from typing import Callable, List, NamedTuple

UUID_PATTERN = re.compile(
    rb"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-"
    rb"[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"
)

GENERATED_CALL_ID_PATTERN = re.compile(rb"call_[0-9a-f]{16}")

# The exact opening of one entry in a V1 `tool_call_request` approvals
# list. Both ids are auto-increment database primary keys, so their
# values depend on how many rows the test database issued earlier. The
# pattern is anchored on the surrounding field names and their order: a
# change to either leaves the raw ids in place, and the comparison fails.
APPROVAL_ENTRY_PATTERN = re.compile(
    rb'\{"id": "(\d+)", "tool_id": "(\d+)", "tool_name":'
)

# Wall-clock seconds a tool has been running, carried by the heartbeat
# events the V2 loop emits while it waits. The field name and the
# position of the event stay compared; only the reading is dropped.
ELAPSED_SECONDS_PATTERN = re.compile(rb'"elapsed_seconds": \d+')
ELAPSED_SECONDS_PLACEHOLDER = b'"elapsed_seconds": <elapsed-seconds>'


class NormalizationRule(NamedTuple):
    """One declared rewrite, applied to the raw transcript bytes."""

    name: str
    description: str
    apply: Callable[[bytes], bytes]


def _stable_placeholders(pattern: re.Pattern, label: bytes) -> Callable[[bytes], bytes]:
    """Replace each distinct match with `<label-N>`.

    Numbering follows first appearance, so the transcript still encodes
    which occurrences refer to the same entity and in which order those
    entities were first emitted.
    """

    def _apply(raw: bytes) -> bytes:
        assigned: dict = {}

        def _substitute(match: re.Match) -> bytes:
            value = match.group(0)
            if value not in assigned:
                assigned[value] = b"<" + label + b"-" + str(len(assigned) + 1).encode() + b">"
            return assigned[value]

        return pattern.sub(_substitute, raw)

    return _apply


def _normalize_approval_primary_keys(raw: bytes) -> bytes:
    """Replace the two database primary keys of each approval entry."""
    approval_ids: dict = {}
    tool_ids: dict = {}

    def _placeholder(assigned: dict, label: bytes, value: bytes) -> bytes:
        if value not in assigned:
            assigned[value] = b"<" + label + b"-" + str(len(assigned) + 1).encode() + b">"
        return assigned[value]

    def _substitute(match: re.Match) -> bytes:
        approval_id = _placeholder(approval_ids, b"approval-pk", match.group(1))
        tool_id = _placeholder(tool_ids, b"mcp-tool-pk", match.group(2))
        return b'{"id": "' + approval_id + b'", "tool_id": "' + tool_id + b'", "tool_name":'

    return APPROVAL_ENTRY_PATTERN.sub(_substitute, raw)


NORMALIZATION_RULES: List[NormalizationRule] = [
    NormalizationRule(
        name="uuid",
        description=(
            "RFC-4122 UUIDs generated by the code under test (database "
            "primary keys such as MCP tool approval ids) become "
            "<uuid-N>, numbered by first appearance."
        ),
        apply=_stable_placeholders(UUID_PATTERN, b"uuid"),
    ),
    NormalizationRule(
        name="generated_tool_call_id",
        description=(
            "Tool call ids the V1 loop synthesizes for calls that arrive "
            "without one (call_<16 hex chars>) become <call-id-N>, "
            "numbered by first appearance."
        ),
        apply=_stable_placeholders(GENERATED_CALL_ID_PATTERN, b"call-id"),
    ),
    NormalizationRule(
        name="approval_primary_keys",
        description=(
            "The auto-increment primary keys of an MCP tool approval and "
            "its tool, inside a V1 tool_call_request approvals entry, "
            "become <approval-pk-N> and <mcp-tool-pk-N>."
        ),
        apply=_normalize_approval_primary_keys,
    ),
    NormalizationRule(
        name="tool_heartbeat_elapsed_seconds",
        description=(
            "The wall-clock reading in a V2 tool heartbeat becomes "
            "<elapsed-seconds>."
        ),
        apply=lambda raw: ELAPSED_SECONDS_PATTERN.sub(ELAPSED_SECONDS_PLACEHOLDER, raw),
    ),
]


def normalize(raw: bytes) -> bytes:
    """Apply every declared rule, in order, to a captured transcript."""
    for rule in NORMALIZATION_RULES:
        raw = rule.apply(raw)
    return raw
