apiVersion: v1
kind: Service
metadata:
  name: user-preferences
  namespace: sterna
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
  selector:
    app: user-preferences
