# Generated by Django 5.1 on 2025-10-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Profile picture URL from OAuth provider', max_length=500, null=True, verbose_name='avatar URL'),
        ),
    ]
