# Generated by Django 5.1 on 2025-10-13 15:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub')], max_length=50)),
                ('provider_user_id', models.CharField(help_text='Unique ID from the OAuth provider (google_id, github_id)', max_length=255)),
                ('email', models.EmailField(help_text='Email used with this provider', max_length=254)),
                ('username', models.CharField(blank=True, help_text='Username from provider (GitHub, etc.)', max_length=255)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional provider-specific data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, help_text='Last time this provider was used to login', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'social account',
                'verbose_name_plural': 'social accounts',
                'db_table': 'auth_social_account',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'provider'], name='auth_social_user_id_2a0d99_idx'), models.Index(fields=['provider', 'provider_user_id'], name='auth_social_provide_b98f1f_idx')],
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
    ]
