# Generated by Django 5.1 on 2025-10-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_socialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata (provider info, etc.)'),
        ),
    ]
