# Generated by Django 5.1 on 2025-10-13 15:07

from django.db import migrations


def populate_social_accounts(apps, schema_editor):
    """Populate SocialAccount records from existing RefreshToken metadata."""
    RefreshToken = apps.get_model('authentication', 'RefreshToken')
    SocialAccount = apps.get_model('authentication', 'SocialAccount')

    # Get all refresh tokens with provider metadata
    tokens_with_provider = RefreshToken.objects.filter(
        metadata__provider__isnull=False
    ).select_related('user')

    # Track created accounts to avoid duplicates
    created_accounts = set()

    for token in tokens_with_provider:
        provider = token.metadata.get('provider')
        if not provider:
            continue

        # Create unique key for user+provider
        account_key = (str(token.user_id), provider)

        # Skip if already created in this migration
        if account_key in created_accounts:
            continue

        # Extract provider-specific data
        if provider == 'google':
            provider_user_id = token.metadata.get('google_id', '')
            username = ''
            avatar_url = token.metadata.get('picture', '')
            extra_data = {
                'picture': token.metadata.get('picture', ''),
            }
        elif provider == 'github':
            provider_user_id = token.metadata.get('github_id', '')
            username = token.metadata.get('username', '')
            avatar_url = token.metadata.get('avatar_url', '')
            extra_data = {}
        else:
            # Unknown provider, skip
            continue

        # Skip if no provider_user_id
        if not provider_user_id:
            continue

        # Create SocialAccount if it doesn't exist
        social_account, created = SocialAccount.objects.get_or_create(
            user=token.user,
            provider=provider,
            defaults={
                'provider_user_id': provider_user_id,
                'email': token.user.email,
                'username': username,
                'avatar_url': avatar_url,
                'extra_data': extra_data,
                'last_login': token.last_used or token.created_at,
            }
        )

        if created:
            created_accounts.add(account_key)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_refreshtoken_metadata'),
    ]

    operations = [
        migrations.RunPython(populate_social_accounts, migrations.RunPython.noop),
    ]
