# Generated by Django 5.1 on 2026-01-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_preferred_image_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_video_model',
            field=models.CharField(choices=[('openai/sora-2', 'Sora 2 (Standard)'), ('openai/sora-2-pro', 'Sora 2 Pro'), ('runway/gen4-turbo', 'Runway Gen-4 Turbo (Fast)'), ('runway/gen4', 'Runway Gen-4 (Quality)')], default='runway/gen4-turbo', help_text='Preferred model for video generation', max_length=255),
        ),
    ]
