# Generated by Django 5.1 on 2026-01-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_add_preferred_video_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_video_model',
            field=models.CharField(choices=[('openai/sora-2', 'Sora 2 (Standard)'), ('openai/sora-2-pro', 'Sora 2 Pro'), ('runway/veo3.1-fast', 'Veo 3.1 Fast'), ('runway/veo3.1', 'Veo 3.1 (Quality)')], default='runway/veo3.1-fast', help_text='Preferred model for video generation', max_length=255),
        ),
    ]
