# Generated by Django 5.1 on 2026-05-21 13:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_consentrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymized_user_token', models.CharField(db_index=True, max_length=64)),
                ('month', models.DateField(db_index=True)),
                ('total_charged_usd', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('tax_collected_usd', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_summary',
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['month'], name='billing_sum_month_f98e79_idx'), models.Index(fields=['anonymized_user_token'], name='billing_sum_anonymi_68ccfc_idx')],
                'unique_together': {('anonymized_user_token', 'month', 'country_code')},
            },
        ),
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email_snapshot', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_token_jti', models.CharField(max_length=64, unique=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_account_deletion_request',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='auth_accoun_status_1c809f_idx'), models.Index(fields=['user', '-requested_at'], name='auth_accoun_user_id_80081c_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataExportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.TextField(blank=True)),
                ('download_url', models.TextField(blank=True)),
                ('download_url_expires_at', models.DateTimeField(blank=True, null=True)),
                ('r2_key', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_export_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_data_export_request',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', '-requested_at'], name='auth_data_e_user_id_c27fcb_idx'), models.Index(fields=['status', 'ready_at'], name='auth_data_e_status_5317ae_idx')],
            },
        ),
    ]
