# Generated by Django 5.2.16 on 2026-08-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_user_provider_api_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tos_accepted_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_image_model',
            field=models.CharField(choices=[('google/gemini-2.5-flash-image', 'Nano Banana (Fast)'), ('google/gemini-3-pro-image-preview', 'Nano Banana Pro (Quality)')], default='google/gemini-2.5-flash-image', help_text='Preferred model for image generation', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_video_model',
            field=models.CharField(blank=True, default='runway/veo3.1-fast', help_text='Preferred model for video generation (validated against VideoModelCatalog)', max_length=255),
        ),
    ]
