# Generated by Django 5.1 on 2026-02-02 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='knowledgechunk',
            new_name='knowledge_b_user_id_d76e01_idx',
            old_name='knowledge_b_user_doc_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgechunk',
            new_name='knowledge_b_documen_f5b49b_idx',
            old_name='knowledge_b_doc_chunk_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgedocument',
            new_name='knowledge_b_user_id_76d1e9_idx',
            old_name='knowledge_b_user_id_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgedocument',
            new_name='knowledge_b_user_id_87a2b5_idx',
            old_name='knowledge_b_user_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgedocument',
            new_name='knowledge_b_user_id_117e2a_idx',
            old_name='knowledge_b_user_id_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgequerylog',
            new_name='knowledge_b_user_id_93d51d_idx',
            old_name='knowledge_b_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgequerylog',
            new_name='knowledge_b_user_id_cb2234_idx',
            old_name='knowledge_b_user_inv_idx',
        ),
    ]
