# Generated by Django 5.1 on 2026-02-02 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_update_embedding_dimensions_3072'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgebasesettings',
            name='auto_query',
        ),
    ]
