# Generated by Django 5.1 on 2025-10-05 14:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsiglierSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_group_id', models.CharField(help_text='ID of the ChatGroup being analyzed (from frontend localStorage)', max_length=255)),
                ('chat_group_data', models.JSONField(help_text='Full ChatGroup data for analysis')),
                ('current_model_at_start', models.CharField(help_text='Model selected when session started', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consigliere_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsigliereMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Consigliere')], max_length=20)),
                ('content', models.TextField()),
                ('model_used', models.CharField(blank=True, help_text='Model used to generate this response', max_length=255, null=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('latency', models.FloatField(blank=True, help_text='Response latency in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='consigliere.consigliersession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_type', models.CharField(help_text="Detected conversation type (e.g., 'technical_discussion', 'creative_writing')", max_length=100)),
                ('total_messages', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('avg_cost_per_message', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('avg_latency', models.FloatField(blank=True, help_text='Average response latency in seconds', null=True)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('insights', models.JSONField(default=list, help_text='List of key insights about the conversation')),
                ('detected_needs', models.JSONField(default=dict, help_text='Detected user needs (e.g., creativity, precision, speed)')),
                ('user_preferences', models.JSONField(default=dict, help_text='User-specified preferences (budget, priority)')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='consigliere.consigliersession')),
            ],
            options={
                'verbose_name_plural': 'Conversation analyses',
            },
        ),
        migrations.CreateModel(
            name='ModelRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_id', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=100)),
                ('score', models.FloatField(help_text='Overall recommendation score (0-1)')),
                ('rank', models.IntegerField(help_text='Rank in the recommendation list (1 = best)')),
                ('reasoning', models.TextField(help_text='Explanation of why this model is recommended')),
                ('tradeoffs', models.JSONField(default=dict, help_text='Trade-offs vs current model (cost_savings, quality_delta, speed_delta)')),
                ('estimated_cost_per_message', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('estimated_quality_score', models.FloatField(blank=True, help_text='Estimated quality score (0-1)', null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='consigliere.conversationanalysis')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.AddIndex(
            model_name='consigliersession',
            index=models.Index(fields=['user', '-created_at'], name='consigliere_user_id_e3a6e0_idx'),
        ),
        migrations.AddIndex(
            model_name='consigliersession',
            index=models.Index(fields=['chat_group_id'], name='consigliere_chat_gr_773a85_idx'),
        ),
        migrations.AddIndex(
            model_name='consiglieremessage',
            index=models.Index(fields=['session', 'created_at'], name='consigliere_session_9be274_idx'),
        ),
        migrations.AddIndex(
            model_name='modelrecommendation',
            index=models.Index(fields=['analysis', 'rank'], name='consigliere_analysi_87c8a7_idx'),
        ),
    ]
