# Generated by Django 5.1 on 2025-10-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consigliere', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationanalysis',
            name='recommended_model_from_conversation',
            field=models.JSONField(blank=True, default=dict, help_text='Best model chosen from those actually used in the conversation', null=True),
        ),
    ]
