# Generated by Django 5.1 on 2025-10-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consigliere', '0002_conversationanalysis_recommended_model_from_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consiglieremessage',
            name='completion_cost',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Cost for completion tokens', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='consiglieremessage',
            name='prompt_cost',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Cost for prompt tokens', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='consiglieremessage',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Total cost (prompt + completion)', max_digits=10, null=True),
        ),
    ]
