# Generated by Django 5.1 on 2025-10-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consigliere', '0003_consiglieremessage_completion_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consiglieremessage',
            name='model_icon_slug',
            field=models.CharField(blank=True, help_text='Model icon slug from LobeHub', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consiglieremessage',
            name='model_icon_url',
            field=models.CharField(blank=True, help_text='Full URL to model icon', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='consiglieremessage',
            name='model_id',
            field=models.CharField(blank=True, help_text='Model ID (extracted from model_used)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consiglieremessage',
            name='provider',
            field=models.CharField(blank=True, help_text='Provider name (extracted from model_used)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consiglieremessage',
            name='provider_icon_slug',
            field=models.CharField(blank=True, help_text='Provider icon slug from LobeHub', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consiglieremessage',
            name='provider_icon_url',
            field=models.CharField(blank=True, help_text='Full URL to provider icon', max_length=512, null=True),
        ),
    ]
