# Generated by Django 5.1 on 2025-10-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consigliere', '0004_consiglieremessage_model_icon_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consiglieremessage',
            name='completion_tokens',
            field=models.IntegerField(blank=True, help_text='Number of tokens in the completion', null=True),
        ),
        migrations.AddField(
            model_name='consiglieremessage',
            name='prompt_tokens',
            field=models.IntegerField(blank=True, help_text='Number of tokens in the prompt', null=True),
        ),
    ]
