apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: sterna
  labels:
    app: orchestrator
    app.kubernetes.io/name: orchestrator
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8003
      targetPort: http
      protocol: TCP
  selector:
    app: orchestrator
