/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRoomsRouteImport } from './routes/voice-rooms'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SparksRouteImport } from './routes/sparks'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as ImagesRouteImport } from './routes/images'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CreationsRouteImport } from './routes/creations'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as LandingRouteImport } from './routes/_landing'
import { Route as ModelsIndexRouteImport } from './routes/models.index'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as SettingsPrivacyRouteImport } from './routes/settings.privacy'
import { Route as SettingsBillingRouteImport } from './routes/settings.billing'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalRefundsRouteImport } from './routes/legal.refunds'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalDpaRouteImport } from './routes/legal.dpa'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalAupRouteImport } from './routes/legal.aup'
import { Route as BillingReturnRouteImport } from './routes/billing.return'
import { Route as AccountRestoreRouteImport } from './routes/account.restore'
import { Route as LandingPricingRouteImport } from './routes/_landing/pricing'

const VoiceRoomsRoute = VoiceRoomsRouteImport.update({
  id: '/voice-rooms',
  path: '/voice-rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SparksRoute = SparksRouteImport.update({
  id: '/sparks',
  path: '/sparks',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesRoute = ImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationsRoute = CreationsRouteImport.update({
  id: '/creations',
  path: '/creations',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRoute,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/settings/privacy',
  path: '/settings/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundsRoute = LegalRefundsRouteImport.update({
  id: '/legal/refunds',
  path: '/legal/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDpaRoute = LegalDpaRouteImport.update({
  id: '/legal/dpa',
  path: '/legal/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAupRoute = LegalAupRouteImport.update({
  id: '/legal/aup',
  path: '/legal/aup',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingReturnRoute = BillingReturnRouteImport.update({
  id: '/billing/return',
  path: '/billing/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRestoreRoute = AccountRestoreRouteImport.update({
  id: '/account/restore',
  path: '/account/restore',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPricingRoute = LandingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => LandingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LandingIndexRoute
  '/agents': typeof AgentsRoute
  '/chats': typeof ChatsRoute
  '/connectors': typeof ConnectorsRoute
  '/creations': typeof CreationsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/images': typeof ImagesRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sparks': typeof SparksRoute
  '/verify-email': typeof VerifyEmailRoute
  '/videos': typeof VideosRoute
  '/voice-rooms': typeof VoiceRoomsRoute
  '/pricing': typeof LandingPricingRoute
  '/account/restore': typeof AccountRestoreRoute
  '/billing/return': typeof BillingReturnRoute
  '/legal/aup': typeof LegalAupRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/models/': typeof ModelsIndexRoute
}
export interface FileRoutesByTo {
  '/agents': typeof AgentsRoute
  '/chats': typeof ChatsRoute
  '/connectors': typeof ConnectorsRoute
  '/creations': typeof CreationsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/images': typeof ImagesRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sparks': typeof SparksRoute
  '/verify-email': typeof VerifyEmailRoute
  '/videos': typeof VideosRoute
  '/voice-rooms': typeof VoiceRoomsRoute
  '/pricing': typeof LandingPricingRoute
  '/account/restore': typeof AccountRestoreRoute
  '/billing/return': typeof BillingReturnRoute
  '/legal/aup': typeof LegalAupRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/': typeof LandingIndexRoute
  '/models': typeof ModelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_landing': typeof LandingRouteWithChildren
  '/agents': typeof AgentsRoute
  '/chats': typeof ChatsRoute
  '/connectors': typeof ConnectorsRoute
  '/creations': typeof CreationsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/images': typeof ImagesRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sparks': typeof SparksRoute
  '/verify-email': typeof VerifyEmailRoute
  '/videos': typeof VideosRoute
  '/voice-rooms': typeof VoiceRoomsRoute
  '/_landing/pricing': typeof LandingPricingRoute
  '/account/restore': typeof AccountRestoreRoute
  '/billing/return': typeof BillingReturnRoute
  '/legal/aup': typeof LegalAupRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/_landing/': typeof LandingIndexRoute
  '/models/': typeof ModelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/chats'
    | '/connectors'
    | '/creations'
    | '/forgot-password'
    | '/images'
    | '/knowledge'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/sparks'
    | '/verify-email'
    | '/videos'
    | '/voice-rooms'
    | '/pricing'
    | '/account/restore'
    | '/billing/return'
    | '/legal/aup'
    | '/legal/cookies'
    | '/legal/dpa'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/oauth/callback'
    | '/settings/billing'
    | '/settings/privacy'
    | '/models/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agents'
    | '/chats'
    | '/connectors'
    | '/creations'
    | '/forgot-password'
    | '/images'
    | '/knowledge'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/sparks'
    | '/verify-email'
    | '/videos'
    | '/voice-rooms'
    | '/pricing'
    | '/account/restore'
    | '/billing/return'
    | '/legal/aup'
    | '/legal/cookies'
    | '/legal/dpa'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/oauth/callback'
    | '/settings/billing'
    | '/settings/privacy'
    | '/'
    | '/models'
  id:
    | '__root__'
    | '/_landing'
    | '/agents'
    | '/chats'
    | '/connectors'
    | '/creations'
    | '/forgot-password'
    | '/images'
    | '/knowledge'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/sparks'
    | '/verify-email'
    | '/videos'
    | '/voice-rooms'
    | '/_landing/pricing'
    | '/account/restore'
    | '/billing/return'
    | '/legal/aup'
    | '/legal/cookies'
    | '/legal/dpa'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/oauth/callback'
    | '/settings/billing'
    | '/settings/privacy'
    | '/_landing/'
    | '/models/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LandingRoute: typeof LandingRouteWithChildren
  AgentsRoute: typeof AgentsRoute
  ChatsRoute: typeof ChatsRoute
  ConnectorsRoute: typeof ConnectorsRoute
  CreationsRoute: typeof CreationsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ImagesRoute: typeof ImagesRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  SparksRoute: typeof SparksRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  VideosRoute: typeof VideosRoute
  VoiceRoomsRoute: typeof VoiceRoomsRoute
  AccountRestoreRoute: typeof AccountRestoreRoute
  BillingReturnRoute: typeof BillingReturnRoute
  LegalAupRoute: typeof LegalAupRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalDpaRoute: typeof LegalDpaRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundsRoute: typeof LegalRefundsRoute
  LegalTermsRoute: typeof LegalTermsRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice-rooms': {
      id: '/voice-rooms'
      path: '/voice-rooms'
      fullPath: '/voice-rooms'
      preLoaderRoute: typeof VoiceRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sparks': {
      id: '/sparks'
      path: '/sparks'
      fullPath: '/sparks'
      preLoaderRoute: typeof SparksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images': {
      id: '/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creations': {
      id: '/creations'
      path: '/creations'
      fullPath: '/creations'
      preLoaderRoute: typeof CreationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refunds': {
      id: '/legal/refunds'
      path: '/legal/refunds'
      fullPath: '/legal/refunds'
      preLoaderRoute: typeof LegalRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/dpa': {
      id: '/legal/dpa'
      path: '/legal/dpa'
      fullPath: '/legal/dpa'
      preLoaderRoute: typeof LegalDpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/aup': {
      id: '/legal/aup'
      path: '/legal/aup'
      fullPath: '/legal/aup'
      preLoaderRoute: typeof LegalAupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/return': {
      id: '/billing/return'
      path: '/billing/return'
      fullPath: '/billing/return'
      preLoaderRoute: typeof BillingReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/restore': {
      id: '/account/restore'
      path: '/account/restore'
      fullPath: '/account/restore'
      preLoaderRoute: typeof AccountRestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/pricing': {
      id: '/_landing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof LandingPricingRouteImport
      parentRoute: typeof LandingRoute
    }
  }
}

interface LandingRouteChildren {
  LandingPricingRoute: typeof LandingPricingRoute
  LandingIndexRoute: typeof LandingIndexRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingPricingRoute: LandingPricingRoute,
  LandingIndexRoute: LandingIndexRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LandingRoute: LandingRouteWithChildren,
  AgentsRoute: AgentsRoute,
  ChatsRoute: ChatsRoute,
  ConnectorsRoute: ConnectorsRoute,
  CreationsRoute: CreationsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ImagesRoute: ImagesRoute,
  KnowledgeRoute: KnowledgeRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  SparksRoute: SparksRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  VideosRoute: VideosRoute,
  VoiceRoomsRoute: VoiceRoomsRoute,
  AccountRestoreRoute: AccountRestoreRoute,
  BillingReturnRoute: BillingReturnRoute,
  LegalAupRoute: LegalAupRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalDpaRoute: LegalDpaRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundsRoute: LegalRefundsRoute,
  LegalTermsRoute: LegalTermsRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  ModelsIndexRoute: ModelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
