# Generated by Django 5.1 on 2025-09-15 15:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelCatalog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("provider", models.CharField(max_length=100)),
                (
                    "prompt_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Price per 1k prompt tokens",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "completion_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Price per 1k completion tokens",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("max_tokens", models.IntegerField(blank=True, null=True)),
                ("supports_streaming", models.BooleanField(default=True)),
                ("supports_functions", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_available", models.BooleanField(default=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["provider", "name"],
                "indexes": [
                    models.Index(
                        fields=["provider"], name="llm_modelca_provide_ee211f_idx"
                    ),
                    models.Index(
                        fields=["is_available"], name="llm_modelca_is_avai_3fd268_idx"
                    ),
                ],
            },
        ),
    ]
