# Generated by Django 5.1 on 2025-10-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_add_endpoint_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcatalog',
            name='supports_prompt_caching',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelcatalog',
            name='supports_stream_cancellation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelcatalog',
            name='supports_web_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='modelcatalog',
            name='completion_price',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Price per 1K completion tokens (internal storage)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='modelcatalog',
            name='prompt_price',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Price per 1K prompt tokens (internal storage)', max_digits=10, null=True),
        ),
    ]
