# Generated by Django 5.1 on 2025-11-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_modelcatalog_supports_prompt_caching_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcatalog',
            name='first_seen_at',
            field=models.DateTimeField(blank=True, help_text='When this model was first seen in OpenRouter catalog', null=True),
        ),
    ]
