# Generated by Django 5.1 on 2026-01-31 20:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0007_videomodelcatalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModelCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_id', models.CharField(help_text="Unique identifier (e.g., 'openai/dall-e-3', 'bfl/flux-1.1-pro')", max_length=255, unique=True)),
                ('name', models.CharField(help_text='Display name', max_length=255)),
                ('provider', models.CharField(help_text='Provider name (openai, bfl, stability, etc.)', max_length=100)),
                ('price_per_image', models.DecimalField(blank=True, decimal_places=6, help_text='Base price per generated image in USD', max_digits=10, null=True)),
                ('price_per_megapixel', models.DecimalField(blank=True, decimal_places=6, help_text='Price per megapixel (for resolution-based pricing)', max_digits=10, null=True)),
                ('supports_generation', models.BooleanField(default=True, help_text='Whether model supports image generation from text')),
                ('supports_editing', models.BooleanField(default=False, help_text='Whether model supports image editing/inpainting')),
                ('supports_variations', models.BooleanField(default=False, help_text='Whether model supports creating image variations')),
                ('supports_outpainting', models.BooleanField(default=False, help_text='Whether model supports outpainting/extending images')),
                ('supports_upscaling', models.BooleanField(default=False, help_text='Whether model supports image upscaling')),
                ('supported_sizes', models.JSONField(blank=True, default=list, help_text="List of supported image sizes (e.g., ['1024x1024', '1792x1024'])")),
                ('supported_aspect_ratios', models.JSONField(blank=True, default=list, help_text="List of supported aspect ratios (e.g., ['1:1', '16:9', '9:16'])")),
                ('max_resolution', models.IntegerField(blank=True, help_text='Maximum resolution in pixels (width * height)', null=True)),
                ('supported_qualities', models.JSONField(blank=True, default=list, help_text="List of quality options (e.g., ['standard', 'hd'])")),
                ('supported_styles', models.JSONField(blank=True, default=list, help_text="List of style presets (e.g., ['vivid', 'natural'])")),
                ('max_images_per_request', models.IntegerField(default=1, help_text='Maximum number of images per request')),
                ('max_prompt_length', models.IntegerField(blank=True, help_text='Maximum prompt length in characters', null=True)),
                ('typical_generation_time_ms', models.IntegerField(blank=True, help_text='Typical generation time in milliseconds', null=True)),
                ('is_fast', models.BooleanField(default=False, help_text='Whether this is a fast/turbo model variant')),
                ('best_for_text', models.BooleanField(default=False, help_text='Whether model excels at rendering text in images')),
                ('best_for_photorealism', models.BooleanField(default=False, help_text='Whether model excels at photorealistic images')),
                ('best_for_illustration', models.BooleanField(default=False, help_text='Whether model excels at illustrations/art')),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_available', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField(blank=True, help_text='When this model was first added to the catalog', null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image Model',
                'verbose_name_plural': 'Image Models',
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.RenameIndex(
            model_name='openrouterusagelog',
            new_name='llm_openrou_user_id_2eb5d4_idx',
            old_name='llm_openrou_user_id_d5d64c_idx',
        ),
        migrations.RenameIndex(
            model_name='openrouterusagelog',
            new_name='llm_openrou_user_id_23fb72_idx',
            old_name='llm_openrou_user_id_29c0c0_idx',
        ),
        migrations.RenameIndex(
            model_name='openrouterusagelog',
            new_name='llm_openrou_request_f78aa3_idx',
            old_name='llm_openrou_request_4dbc67_idx',
        ),
        migrations.RenameIndex(
            model_name='videomodelcatalog',
            new_name='llm_videomo_provide_4a108d_idx',
            old_name='llm_videomo_provide_4e5e3c_idx',
        ),
        migrations.RenameIndex(
            model_name='videomodelcatalog',
            new_name='llm_videomo_is_acti_c62f15_idx',
            old_name='llm_videomo_is_acti_f5e8d3_idx',
        ),
        migrations.RenameIndex(
            model_name='videomodelcatalog',
            new_name='llm_videomo_input_t_987594_idx',
            old_name='llm_videomo_input_t_8a7c2f_idx',
        ),
        migrations.RenameIndex(
            model_name='videomodelcatalog',
            new_name='llm_videomo_sort_or_8f5c82_idx',
            old_name='llm_videomo_sort_or_d9e1a4_idx',
        ),
        migrations.AlterField(
            model_name='videomodelcatalog',
            name='capabilities',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible capabilities dict. Expected structure:\n        {\n            "supports_audio": bool,\n            "supports_lip_sync": bool,\n            "min_duration": int,\n            "max_duration": int,\n            "valid_durations": [int],\n            "supported_resolutions": ["720p", "1080p", "4K"],\n            "supported_aspect_ratios": ["16:9", "9:16", "1:1"],\n            "supported_fps": [24, 30, 60],\n            "max_input_size_mb": int,\n            "upscale_factor": int (for upscaling models),\n            "supported_input_formats": ["jpeg", "png", "webp", "mp4"],\n            "supported_audio_formats": ["mp3", "wav", "flac"],\n            "output_format": "mp4"\n        }'),
        ),
        migrations.AddIndex(
            model_name='imagemodelcatalog',
            index=models.Index(fields=['provider'], name='llm_imagemo_provide_389d26_idx'),
        ),
        migrations.AddIndex(
            model_name='imagemodelcatalog',
            index=models.Index(fields=['is_available'], name='llm_imagemo_is_avai_d4b15e_idx'),
        ),
    ]
