# Generated by Django 5.1 on 2026-02-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0010_sterna_routing'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sternaroutingpool',
            new_name='llm_sternar_is_acti_a8afbf_idx',
            old_name='llm_sternaro_is_acti_idx',
        ),
        migrations.RemoveField(
            model_name='modelcatalog',
            name='supports_web_search',
        ),
        migrations.AlterField(
            model_name='sternaconversationscore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sternaroutinglog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sternaroutingpool',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
