# Generated by Django 5.1 on 2025-10-20 11:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this server', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this server provides')),
                ('transport_type', models.CharField(choices=[('stdio', 'Standard I/O'), ('websocket', 'WebSocket')], default='websocket', help_text='Transport protocol to use', max_length=20)),
                ('url', models.CharField(blank=True, help_text='WebSocket URL (e.g., wss://mcp.example.com)', max_length=500, validators=[django.core.validators.URLValidator(schemes=['ws', 'wss', 'http', 'https'])])),
                ('command', models.CharField(blank=True, help_text="Command to execute for stdio transport (e.g., 'npx @modelcontextprotocol/server-example')", max_length=500)),
                ('working_directory', models.CharField(blank=True, help_text='Working directory for stdio command', max_length=500)),
                ('auth_config', models.JSONField(blank=True, default=dict, help_text='Authentication configuration (API keys, tokens, etc.)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this server is currently enabled')),
                ('last_connected', models.DateTimeField(blank=True, help_text='Last successful connection timestamp', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Last connection error message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this server configuration', on_delete=django.db.models.deletion.CASCADE, related_name='mcp_servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MCPTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tool name (unique per server)', max_length=200)),
                ('description', models.TextField(help_text='What this tool does')),
                ('input_schema', models.JSONField(help_text='JSON Schema for tool inputs')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional tool metadata from MCP server')),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_refreshed', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(help_text='MCP server that provides this tool', on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='mcp.mcpserver')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MCPToolApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, help_text='Associated chat session ID', max_length=100)),
                ('proposed_arguments', models.JSONField(help_text='Arguments that would be passed to the tool')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status', max_length=20)),
                ('scope', models.CharField(choices=[('once', 'Single Use'), ('session', 'Current Session'), ('permanent', 'Always Allow')], default='once', help_text='How long this approval is valid', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, help_text='When the approval decision was made', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this approval expires (for session scope)', null=True)),
                ('tool', models.ForeignKey(help_text='Tool being approved/rejected', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='mcp.mcptool')),
                ('user', models.ForeignKey(help_text='User making the approval decision', on_delete=django.db.models.deletion.CASCADE, related_name='mcp_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='MCPToolExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, help_text='Associated chat session ID', max_length=100)),
                ('arguments', models.JSONField(help_text='Arguments passed to the tool')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout'), ('cancelled', 'Cancelled')], default='pending', help_text='Current execution status', max_length=20)),
                ('result', models.JSONField(blank=True, help_text='Tool output (if successful)', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message (if failed)')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When execution completed (success or failure)', null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Execution duration in milliseconds', null=True)),
                ('approval', models.ForeignKey(blank=True, help_text='Associated approval (if required)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='mcp.mcptoolapproval')),
                ('tool', models.ForeignKey(help_text='Tool that was executed', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='mcp.mcptool')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mcpserver',
            index=models.Index(fields=['user', 'is_active'], name='mcp_mcpserv_user_id_94b758_idx'),
        ),
        migrations.AddConstraint(
            model_name='mcpserver',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('transport_type', 'websocket'), ('url__isnull', False)), models.Q(('command__isnull', False), ('transport_type', 'stdio')), _connector='OR'), name='mcp_server_transport_config'),
        ),
        migrations.AddIndex(
            model_name='mcptool',
            index=models.Index(fields=['server', 'name'], name='mcp_mcptool_server__dff253_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mcptool',
            unique_together={('server', 'name')},
        ),
        migrations.AddIndex(
            model_name='mcptoolapproval',
            index=models.Index(fields=['user', 'status'], name='mcp_mcptool_user_id_c40bb9_idx'),
        ),
        migrations.AddIndex(
            model_name='mcptoolapproval',
            index=models.Index(fields=['session_id', 'status'], name='mcp_mcptool_session_f4dfd4_idx'),
        ),
        migrations.AddIndex(
            model_name='mcptoolexecution',
            index=models.Index(fields=['session_id', 'status'], name='mcp_mcptool_session_ec28e7_idx'),
        ),
        migrations.AddIndex(
            model_name='mcptoolexecution',
            index=models.Index(fields=['tool', 'status'], name='mcp_mcptool_tool_id_4e6bed_idx'),
        ),
    ]
