# Generated by Django 5.1 on 2025-10-20 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mcpserver',
            name='mcp_server_transport_config',
        ),
        migrations.RemoveField(
            model_name='mcpserver',
            name='command',
        ),
        migrations.RemoveField(
            model_name='mcpserver',
            name='working_directory',
        ),
        migrations.AlterField(
            model_name='mcpserver',
            name='transport_type',
            field=models.CharField(choices=[('websocket', 'WebSocket')], default='websocket', help_text='Transport protocol to use', max_length=20),
        ),
        migrations.AlterField(
            model_name='mcpserver',
            name='url',
            field=models.CharField(help_text='WebSocket URL (e.g., ws://localhost:8080 or wss://mcp.example.com)', max_length=500, validators=[django.core.validators.URLValidator(schemes=['ws', 'wss'])]),
        ),
    ]
