# Generated by Django 5.1 on 2025-10-20 14:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0002_remove_mcpserver_mcp_server_transport_config_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Unique identifier (e.g., 'github', 'notion')", unique=True)),
                ('name', models.CharField(help_text="Display name (e.g., 'GitHub')", max_length=100)),
                ('description', models.TextField(help_text='What this connector provides')),
                ('icon_url', models.URLField(blank=True, help_text='URL to connector icon/logo')),
                ('npm_package', models.CharField(help_text="NPM package name (e.g., '@modelcontextprotocol/server-github')", max_length=200)),
                ('command_template', models.CharField(help_text="Command template to run the MCP server (e.g., 'npx -y @modelcontextprotocol/server-github')", max_length=500)),
                ('oauth_provider', models.CharField(help_text="OAuth provider identifier (e.g., 'github', 'notion')", max_length=50)),
                ('oauth_authorize_url', models.URLField(help_text='OAuth authorization endpoint')),
                ('oauth_token_url', models.URLField(help_text='OAuth token exchange endpoint')),
                ('oauth_scopes', models.JSONField(default=list, help_text="Required OAuth scopes (e.g., ['repo', 'user'])")),
                ('env_var_name', models.CharField(help_text="Environment variable name for the OAuth token (e.g., 'GITHUB_PERSONAL_ACCESS_TOKEN')", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this connector is currently available')),
                ('documentation_url', models.URLField(blank=True, help_text='Link to connector documentation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='mcpserver',
            name='command',
            field=models.CharField(blank=True, help_text="Command to run for stdio transport (e.g., 'npx -y @modelcontextprotocol/server-github')", max_length=500),
        ),
        migrations.AddField(
            model_name='mcpserver',
            name='working_directory',
            field=models.CharField(blank=True, help_text='Working directory for stdio process', max_length=500),
        ),
        migrations.AlterField(
            model_name='mcpserver',
            name='transport_type',
            field=models.CharField(choices=[('websocket', 'WebSocket'), ('stdio', 'Standard I/O')], default='websocket', help_text='Transport protocol to use', max_length=20),
        ),
        migrations.AlterField(
            model_name='mcpserver',
            name='url',
            field=models.CharField(blank=True, help_text='WebSocket URL (required for websocket transport)', max_length=500, validators=[django.core.validators.URLValidator(schemes=['ws', 'wss'])]),
        ),
        migrations.CreateModel(
            name='MCPConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text='OAuth access token (will be encrypted)')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token (will be encrypted)')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the access token expires', null=True)),
                ('granted_scopes', models.JSONField(default=list, help_text='OAuth scopes granted by the user')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this connection is currently active')),
                ('last_used', models.DateTimeField(blank=True, help_text='Last time this connection was used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this connection', on_delete=django.db.models.deletion.CASCADE, related_name='mcp_connections', to=settings.AUTH_USER_MODEL)),
                ('connector', models.ForeignKey(help_text='Connector this connection is for', on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='mcp.mcpconnector')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='mcp_mcpconn_user_id_70bedb_idx')],
                'unique_together': {('user', 'connector')},
            },
        ),
    ]
