# Generated by Django 5.1 on 2025-10-20 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0003_mcpconnector_mcpserver_command_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPAuthorizationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Temporary authorization token', max_length=64, unique=True)),
                ('connector_slug', models.CharField(help_text='MCP connector slug', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this token was created')),
                ('expires_at', models.DateTimeField(help_text='When this token expires')),
                ('used_at', models.DateTimeField(blank=True, help_text='When this token was used (null if not used yet)', null=True)),
                ('user', models.ForeignKey(help_text='User who requested authorization', on_delete=django.db.models.deletion.CASCADE, related_name='mcp_auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mcp_authorization_token',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token', 'expires_at'], name='mcp_authori_token_23e8f2_idx'), models.Index(fields=['user', 'created_at'], name='mcp_authori_user_id_6992c4_idx')],
            },
        ),
    ]
