# Generated by Django 5.1 on 2025-10-20 23:04

import mcp.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0004_mcpauthorizationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcpconnection',
            name='access_token',
            field=mcp.fields.EncryptedTextField(help_text='OAuth access token (encrypted at rest)'),
        ),
        migrations.AlterField(
            model_name='mcpconnection',
            name='refresh_token',
            field=mcp.fields.EncryptedTextField(blank=True, help_text='OAuth refresh token (encrypted at rest)'),
        ),
        migrations.AlterField(
            model_name='mcpserver',
            name='auth_config',
            field=mcp.fields.EncryptedJSONField(blank=True, default=dict, help_text='Authentication configuration (API keys, tokens, etc.) - encrypted at rest'),
        ),
    ]
