# Generated by Django 5.1 on 2025-10-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0006_encrypt_oauth_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpserver',
            name='connection_healthy',
            field=models.BooleanField(default=False, help_text='Whether the last health check was successful'),
        ),
        migrations.AddField(
            model_name='mcpserver',
            name='last_health_check',
            field=models.DateTimeField(blank=True, help_text='Last health check attempt timestamp', null=True),
        ),
    ]
