# Generated by Django 5.1 on 2025-10-22 16:38

from django.db import migrations


def add_connection_id_to_servers(apps, schema_editor):
    """Add connection_id to auth_config for existing MCP servers that were created via OAuth."""
    MCPServer = apps.get_model('mcp', 'MCPServer')
    MCPConnection = apps.get_model('mcp', 'MCPConnection')
    MCPConnector = apps.get_model('mcp', 'MCPConnector')

    # Get all connectors to map env_var_name to connector
    connectors = {conn.env_var_name: conn for conn in MCPConnector.objects.all()}

    # Process each server that has auth_config
    updated_count = 0
    for server in MCPServer.objects.filter(auth_config__isnull=False):
        # Skip if already has connection_id
        if server.auth_config.get('connection_id'):
            continue

        # Find which connector this server belongs to by checking auth_config keys
        connector = None
        for env_var_name, conn in connectors.items():
            if env_var_name in server.auth_config:
                connector = conn
                break

        if not connector:
            # This server doesn't have a recognized OAuth token, skip it
            continue

        # Find the matching connection for this user + connector
        try:
            connection = MCPConnection.objects.get(
                user=server.user,
                connector=connector,
                is_active=True
            )

            # Add connection_id to auth_config
            server.auth_config['connection_id'] = str(connection.id)
            server.save(update_fields=['auth_config'])
            updated_count += 1

        except MCPConnection.DoesNotExist:
            # No active connection found, this shouldn't happen but we'll skip
            continue
        except MCPConnection.MultipleObjectsReturned:
            # Multiple connections (shouldn't happen due to unique_together), take first
            connection = MCPConnection.objects.filter(
                user=server.user,
                connector=connector,
                is_active=True
            ).first()

            if connection:
                server.auth_config['connection_id'] = str(connection.id)
                server.save(update_fields=['auth_config'])
                updated_count += 1

    print(f"Updated {updated_count} MCP servers with connection_id")


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0007_add_health_check_fields'),
    ]

    operations = [
        migrations.RunPython(add_connection_id_to_servers, migrations.RunPython.noop),
    ]
