# Generated by Django 5.1 on 2025-12-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0013_mcpserver_user_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpserver',
            name='category',
            field=models.CharField(choices=[('productivity', 'Productivity & Collaboration'), ('developer', 'Developer Tools'), ('cloud', 'Cloud & Infrastructure'), ('crm', 'CRM & Sales'), ('finance', 'Finance & Payments'), ('ai', 'AI & Knowledge'), ('data', 'Data & Analytics'), ('other', 'Other')], default='other', help_text='Category for grouping servers in the UI', max_length=20),
        ),
        migrations.AlterField(
            model_name='mcpserver',
            name='oauth_client_id',
            field=models.CharField(blank=True, help_text='OAuth client ID (from dynamic registration or manual entry)', max_length=500),
        ),
        migrations.AlterField(
            model_name='mcpserver',
            name='transport_type',
            field=models.CharField(choices=[('websocket', 'WebSocket'), ('stdio', 'Standard I/O'), ('http', 'HTTP/SSE (Remote)'), ('sandboxed', 'Sandboxed NPM')], default='websocket', help_text='Transport protocol to use', max_length=20),
        ),
    ]
