# Generated by Django 5.1 on 2025-12-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0014_add_category_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpserver',
            name='icon_invert_in_dark_mode',
            field=models.BooleanField(
                default=False,
                help_text='Whether to invert the icon color in dark mode (for dark/black icons)',
            ),
        ),
    ]
