# Generated by Django 5.1 on 2025-12-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0015_add_icon_invert_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpserver',
            name='is_official',
            field=models.BooleanField(default=True, help_text='Whether this is an official MCP server from the service provider (False = community/unofficial)'),
        ),
    ]
