# Generated by Django 5.1 on 2025-12-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0016_add_is_official_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpserver',
            name='docs_url',
            field=models.URLField(blank=True, help_text='URL to documentation or source code for this MCP server', null=True),
        ),
    ]
