# Generated by Django 5.1 on 2025-12-23 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0017_add_docs_url_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPDiscoverySearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text='The search query/description', max_length=500)),
                ('preconfigured_results', models.JSONField(default=list, help_text='Matching preconfigured servers from our catalog')),
                ('external_results', models.JSONField(default=list, help_text='External servers discovered from web search')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who performed the search', on_delete=django.db.models.deletion.CASCADE, related_name='mcp_discovery_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='mcp_mcpdisc_user_id_c17e98_idx')],
            },
        ),
    ]
