# Generated by Django 5.1 on 2026-07-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0018_add_mcp_discovery_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcpserver',
            name='category',
            field=models.CharField(choices=[('productivity', 'Productivity & Collaboration'), ('developer', 'Developer Tools'), ('cloud', 'Cloud & Infrastructure'), ('crm', 'CRM & Sales'), ('finance', 'Finance & Payments'), ('ai', 'AI & Knowledge'), ('data', 'Data & Analytics'), ('communication', 'Communication & Social'), ('automation', 'Automation & Integration'), ('design', 'Design & Creative'), ('ecommerce', 'E-commerce'), ('utilities', 'Utilities & Tools'), ('other', 'Other')], default='other', help_text='Category for grouping servers in the UI', max_length=20),
        ),
    ]
