# Generated by Django 5.1 on 2026-01-05 00:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('total_size_bytes', models.BigIntegerField(default=0)),
                ('file_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='conversations.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('syncing', 'Syncing'), ('error', 'Error')], default='idle', max_length=20)),
                ('direction', models.CharField(blank=True, choices=[('save', 'Save'), ('restore', 'Restore')], max_length=10, null=True)),
                ('files_total', models.IntegerField(default=0)),
                ('files_synced', models.IntegerField(default=0)),
                ('bytes_total', models.BigIntegerField(default=0)),
                ('bytes_synced', models.BigIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_state', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Sync State',
                'verbose_name_plural': 'Sync States',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=1024)),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=127, null=True)),
                ('size_bytes', models.BigIntegerField()),
                ('storage_type', models.CharField(choices=[('inline', 'Inline (PostgreSQL)'), ('r2', 'R2 (Cloudflare)')], default='inline', max_length=20)),
                ('content', models.BinaryField(blank=True, null=True)),
                ('r2_bucket', models.CharField(blank=True, max_length=63, null=True)),
                ('r2_key', models.CharField(blank=True, max_length=1024, null=True)),
                ('sha256_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('thumbnail', 'Thumbnail'), ('generated', 'AI Generated')], default='image', max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=127)),
                ('size_bytes', models.BigIntegerField()),
                ('storage_type', models.CharField(choices=[('inline', 'Inline (PostgreSQL)'), ('r2', 'R2 (Cloudflare)')], default='r2', max_length=20)),
                ('content', models.BinaryField(blank=True, null=True)),
                ('r2_bucket', models.CharField(blank=True, max_length=63, null=True)),
                ('r2_key', models.CharField(blank=True, help_text='R2 key: {user_id}/chats/{conversation_id}/assets/{asset_id}', max_length=1024, null=True)),
                ('width', models.IntegerField(blank=True, help_text='Image/video width in pixels', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Image/video height in pixels', null=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Video/audio duration', null=True)),
                ('sha256_hash', models.CharField(db_index=True, max_length=64)),
                ('generation_prompt', models.TextField(blank=True, help_text='Prompt used to generate this asset (if AI-generated)', null=True)),
                ('generation_model', models.CharField(blank=True, help_text="Model used to generate this asset (e.g., 'dall-e-3')", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='conversations.conversation')),
                ('message', models.ForeignKey(blank=True, help_text='Optional: specific message this asset is attached to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='conversations.message')),
                ('thumbnail', models.ForeignKey(blank=True, help_text='Thumbnail asset for this video/image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_assets', to='workspaces.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'conversation'], name='workspaces__user_id_553ea8_idx'), models.Index(fields=['conversation', 'message'], name='workspaces__convers_06f284_idx'), models.Index(fields=['asset_type'], name='workspaces__asset_t_d42790_idx'), models.Index(fields=['sha256_hash'], name='workspaces__sha256__0a9d11_idx'), models.Index(fields=['created_at'], name='workspaces__created_28674d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['user'], name='workspaces__user_id_6f11db_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['last_accessed_at'], name='workspaces__last_ac_0a0dd2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workspace',
            unique_together={('user', 'conversation')},
        ),
        migrations.AddIndex(
            model_name='workspacefile',
            index=models.Index(fields=['workspace'], name='workspaces__workspa_ab5b97_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacefile',
            index=models.Index(fields=['sha256_hash'], name='workspaces__sha256__55c9c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workspacefile',
            unique_together={('workspace', 'path')},
        ),
    ]
