# Generated by Django 5.1

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, help_text='URL-safe token for public access', max_length=64, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the link is active (soft delete)')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Optional expiration timestamp', null=True)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this link has been accessed')),
                ('last_viewed_at', models.DateTimeField(blank=True, help_text='Last time someone viewed this shared asset', null=True)),
                ('custom_title', models.CharField(blank=True, help_text='Custom title for social media previews', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(help_text='The asset being shared', on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='workspaces.asset')),
                ('created_by', models.ForeignKey(help_text='User who created the share link', on_delete=django.db.models.deletion.CASCADE, related_name='asset_share_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assetsharelink',
            index=models.Index(fields=['token'], name='workspaces__token_8a4b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='assetsharelink',
            index=models.Index(fields=['asset', 'is_active'], name='workspaces__asset_i_3c7d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='assetsharelink',
            index=models.Index(fields=['created_by', '-created_at'], name='workspaces__created_9f8b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='assetsharelink',
            index=models.Index(fields=['expires_at'], name='workspaces__expires_5d1c4e_idx'),
        ),
    ]
