# Generated by Django 5.1 on 2026-01-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_assetsharelink'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assetsharelink',
            new_name='workspaces__token_1a451f_idx',
            old_name='workspaces__token_8a4b2f_idx',
        ),
        migrations.RenameIndex(
            model_name='assetsharelink',
            new_name='workspaces__asset_i_37bf30_idx',
            old_name='workspaces__asset_i_3c7d1e_idx',
        ),
        migrations.RenameIndex(
            model_name='assetsharelink',
            new_name='workspaces__created_dfe302_idx',
            old_name='workspaces__created_9f8b2a_idx',
        ),
        migrations.RenameIndex(
            model_name='assetsharelink',
            new_name='workspaces__expires_db2e44_idx',
            old_name='workspaces__expires_5d1c4e_idx',
        ),
        migrations.AddField(
            model_name='assetsharelink',
            name='watermark_enabled',
            field=models.BooleanField(default=True, help_text='Whether to apply watermark to shared images'),
        ),
        migrations.AddField(
            model_name='assetsharelink',
            name='watermark_position',
            field=models.CharField(choices=[('bottom-right', 'Bottom Right'), ('bottom-left', 'Bottom Left'), ('top-right', 'Top Right'), ('top-left', 'Top Left')], default='bottom-right', help_text='Position of watermark on image', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('thumbnail', 'Thumbnail'), ('generated', 'AI Generated'), ('document', 'Document')], default='image', max_length=20),
        ),
    ]
