# Generated by Django 5.1 on 2026-01-21 - Manual migration for conversation->chat FK
# This migration changes Workspace and Asset FKs from Conversation to Chat

import django.db.models.deletion
from django.db import migrations, models


def migrate_assets_to_chat(apps, schema_editor):
    """
    Migrate existing assets from conversation_id to chat_id.

    For each asset, find the first chat of its conversation and use that.
    """
    Chat = apps.get_model('conversations', 'Chat')

    # Get all unique conversation IDs from assets
    from django.db import connection
    cursor = connection.cursor()

    # Build a mapping of conversation_id -> first chat_id
    cursor.execute('''
        SELECT DISTINCT conversation_id
        FROM workspaces_asset
        WHERE conversation_id IS NOT NULL
    ''')
    conv_ids = [row[0] for row in cursor.fetchall()]

    for conv_id in conv_ids:
        # Get the first chat for this conversation
        chat = Chat.objects.filter(conversation_id=conv_id).first()
        if chat:
            cursor.execute(
                'UPDATE workspaces_asset SET chat_id = %s WHERE conversation_id = %s',
                [chat.id, conv_id]
            )
            print(f"  Migrated assets from conversation {conv_id} to chat {chat.id}")
        else:
            print(f"  WARNING: No chat found for conversation {conv_id}")


def migrate_workspaces_to_chat(apps, schema_editor):
    """
    Migrate existing workspaces from conversation_id to chat_id.
    """
    Chat = apps.get_model('conversations', 'Chat')

    from django.db import connection
    cursor = connection.cursor()

    cursor.execute('''
        SELECT DISTINCT conversation_id
        FROM workspaces_workspace
        WHERE conversation_id IS NOT NULL
    ''')
    conv_ids = [row[0] for row in cursor.fetchall()]

    for conv_id in conv_ids:
        chat = Chat.objects.filter(conversation_id=conv_id).first()
        if chat:
            cursor.execute(
                'UPDATE workspaces_workspace SET chat_id = %s WHERE conversation_id = %s',
                [chat.id, conv_id]
            )
            print(f"  Migrated workspaces from conversation {conv_id} to chat {chat.id}")
        else:
            print(f"  WARNING: No chat found for conversation {conv_id}")


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
        ('workspaces', '0003_add_watermark_to_sharelink'),
    ]

    operations = [
        # ─────────────────────────────────────────────────────────
        # Workspace: conversation -> chat
        # ─────────────────────────────────────────────────────────

        # 1. Remove unique_together constraint first (required before removing FK)
        migrations.AlterUniqueTogether(
            name='workspace',
            unique_together=set(),
        ),

        # 2. Add the new chat FK as nullable first
        migrations.AddField(
            model_name='workspace',
            name='chat',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='workspaces',
                to='conversations.chat',
                null=True,
            ),
        ),

        # 3. Migrate existing data
        migrations.RunPython(migrate_workspaces_to_chat, migrations.RunPython.noop),

        # 4. Remove the old conversation FK
        migrations.RemoveField(
            model_name='workspace',
            name='conversation',
        ),

        # 5. Make chat FK non-nullable (only works if all data migrated)
        migrations.AlterField(
            model_name='workspace',
            name='chat',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='workspaces',
                to='conversations.chat',
            ),
        ),

        # 6. Add new unique_together constraint
        migrations.AlterUniqueTogether(
            name='workspace',
            unique_together={('user', 'chat')},
        ),

        # ─────────────────────────────────────────────────────────
        # Asset: conversation -> chat
        # ─────────────────────────────────────────────────────────

        # 1. Remove old indexes first
        migrations.RemoveIndex(
            model_name='asset',
            name='workspaces__user_id_553ea8_idx',
        ),
        migrations.RemoveIndex(
            model_name='asset',
            name='workspaces__convers_06f284_idx',
        ),

        # 2. Add the new chat FK as nullable first
        migrations.AddField(
            model_name='asset',
            name='chat',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='assets',
                to='conversations.chat',
                null=True,
            ),
        ),

        # 3. Migrate existing data
        migrations.RunPython(migrate_assets_to_chat, migrations.RunPython.noop),

        # 4. Remove the old conversation FK
        migrations.RemoveField(
            model_name='asset',
            name='conversation',
        ),

        # 5. Make chat FK non-nullable
        migrations.AlterField(
            model_name='asset',
            name='chat',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='assets',
                to='conversations.chat',
            ),
        ),

        # 6. Update r2_key help_text
        migrations.AlterField(
            model_name='asset',
            name='r2_key',
            field=models.CharField(
                blank=True,
                help_text='R2 key: {user_id}/chats/{chat_id}/assets/{asset_id}',
                max_length=1024,
                null=True,
            ),
        ),

        # 7. Add new indexes (names auto-generated by Django)
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['user', 'chat'], name='workspaces__user_id_c07784_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['chat', 'message'], name='workspaces__chat_id_3c3c67_idx'),
        ),

        # 8. Add document type to Asset.TYPE_CHOICES
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(
                choices=[
                    ('image', 'Image'),
                    ('video', 'Video'),
                    ('audio', 'Audio'),
                    ('thumbnail', 'Thumbnail'),
                    ('generated', 'AI Generated'),
                    ('document', 'Document'),
                ],
                default='image',
                max_length=20,
            ),
        ),
    ]
