# Generated by Django 5.1 on 2026-02-03 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_add_file_versioning'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fileversion',
            name='unique_workspace_path_version',
        ),
        migrations.RenameIndex(
            model_name='fileversion',
            new_name='workspaces__workspa_c09253_idx',
            old_name='ws_fv_path_created_idx',
        ),
        migrations.RenameIndex(
            model_name='fileversion',
            new_name='workspaces__workspa_20fbe4_idx',
            old_name='ws_fv_workspace_created_idx',
        ),
        migrations.RenameIndex(
            model_name='fileversion',
            new_name='workspaces__source__edd18e_idx',
            old_name='ws_fv_source_type_idx',
        ),
        migrations.RenameIndex(
            model_name='fileversion',
            new_name='workspaces__source__dca048_idx',
            old_name='ws_fv_source_msg_idx',
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='content_ref',
            field=models.ForeignKey(db_column='sha256_hash', on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='workspaces.fileversioncontent'),
        ),
        migrations.AlterUniqueTogether(
            name='fileversion',
            unique_together={('workspace', 'path', 'version_number')},
        ),
    ]
