# Generated by Django 5.1 on 2025-11-30 18:24

import django.db.models.deletion
import mcp.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Session name (auto-generated or custom)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional session description')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', help_text='Current session status', max_length=20)),
                ('github_repo_full_name', models.CharField(blank=True, help_text='Full repository name: owner/repo', max_length=255)),
                ('github_repo_url', models.URLField(blank=True, help_text='GitHub repository URL')),
                ('github_branch', models.CharField(default='main', help_text='Target branch name', max_length=255)),
                ('repo_cloned', models.BooleanField(default=False, help_text='Whether the repository has been cloned to workspace')),
                ('model_id', models.CharField(default='anthropic/claude-sonnet-4', help_text='Selected LLM model for this session', max_length=255)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Additional session settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True, help_text='Last activity timestamp for sorting')),
                ('user', models.ForeignKey(help_text='User who owns this session', on_delete=django.db.models.deletion.CASCADE, related_name='code_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code Session',
                'verbose_name_plural': 'Code Sessions',
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField(help_text="User's coding request/prompt")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('cloning', 'Cloning Repository'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current job status', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('progress_message', models.CharField(blank=True, help_text='Current progress message for UI display', max_length=500)),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID for this job', max_length=255)),
                ('sandbox_container_id', models.CharField(blank=True, help_text='Docker container ID for the sandbox', max_length=255)),
                ('result', models.JSONField(blank=True, help_text='Job execution result data', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if job failed')),
                ('files_modified', models.JSONField(default=list, help_text='List of files modified during job execution')),
                ('messages', models.JSONField(default=list, help_text='Message history (user, assistant, tool messages)')),
                ('total_tokens', models.IntegerField(default=0, help_text='Total tokens used')),
                ('prompt_tokens', models.IntegerField(default=0, help_text='Prompt tokens used')),
                ('completion_tokens', models.IntegerField(default=0, help_text='Completion tokens used')),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, help_text='Total cost in USD', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the job started execution', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the job completed', null=True)),
                ('session', models.ForeignKey(help_text='Parent session for this job', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='code_sessions.codesession')),
            ],
            options={
                'verbose_name': 'Code Job',
                'verbose_name_plural': 'Code Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GitHubConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', mcp.fields.EncryptedTextField(help_text='Encrypted GitHub OAuth access token')),
                ('refresh_token', mcp.fields.EncryptedTextField(blank=True, default='', help_text='Encrypted OAuth refresh token (if available)')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the access token expires', null=True)),
                ('github_username', models.CharField(help_text='GitHub username', max_length=100)),
                ('github_user_id', models.BigIntegerField(help_text='GitHub user ID')),
                ('avatar_url', models.URLField(blank=True, help_text='GitHub avatar URL')),
                ('scopes', models.JSONField(default=list, help_text='List of granted OAuth scopes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User who owns this GitHub connection', on_delete=django.db.models.deletion.CASCADE, related_name='github_code_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GitHub Connection',
                'verbose_name_plural': 'GitHub Connections',
            },
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', help_text='Log level', max_length=20)),
                ('message', models.TextField(help_text='Log message')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional log metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(help_text='Parent job for this log entry', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='code_sessions.codejob')),
            ],
            options={
                'verbose_name': 'Job Log',
                'verbose_name_plural': 'Job Logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='codesession',
            index=models.Index(fields=['user', 'status'], name='code_sessio_user_id_682628_idx'),
        ),
        migrations.AddIndex(
            model_name='codesession',
            index=models.Index(fields=['user', '-last_activity_at'], name='code_sessio_user_id_3fb27f_idx'),
        ),
        migrations.AddIndex(
            model_name='codejob',
            index=models.Index(fields=['session', 'status'], name='code_sessio_session_0a5bd1_idx'),
        ),
        migrations.AddIndex(
            model_name='codejob',
            index=models.Index(fields=['session', '-created_at'], name='code_sessio_session_13e4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='codejob',
            index=models.Index(fields=['celery_task_id'], name='code_sessio_celery__1cf9dd_idx'),
        ),
        migrations.AddIndex(
            model_name='joblog',
            index=models.Index(fields=['job', 'created_at'], name='code_sessio_job_id_cfca6d_idx'),
        ),
        migrations.AddIndex(
            model_name='joblog',
            index=models.Index(fields=['job', 'level'], name='code_sessio_job_id_309ddd_idx'),
        ),
    ]
