# Generated by Django 5.1 on 2025-11-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codejob',
            name='steps',
            field=models.JSONField(default=list, help_text='Execution steps for UI display (text, tool_executions)'),
        ),
    ]
