# Generated by Django 5.1 on 2025-12-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_sessions', '0002_add_steps_to_codejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='codejob',
            name='pr_body',
            field=models.TextField(blank=True, help_text='Pull request body/description (generated by assistant)'),
        ),
        migrations.AddField(
            model_name='codejob',
            name='pr_ready',
            field=models.BooleanField(default=False, help_text='Whether the assistant has prepared PR metadata'),
        ),
        migrations.AddField(
            model_name='codejob',
            name='pr_title',
            field=models.CharField(blank=True, help_text='Pull request title (generated by assistant)', max_length=255),
        ),
    ]
