# Generated by Django 5.1 on 2025-12-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_sessions', '0003_add_pr_metadata_to_codejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='codejob',
            name='enable_reasoning',
            field=models.BooleanField(default=False, help_text='Whether to enable extended thinking/reasoning for this job'),
        ),
    ]
