# Generated by Django 5.1 on 2026-02-04 22:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_sessions', '0005_add_optimization_metrics'),
        ('conversations', '0005_add_chat_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Human-readable plan title', max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe slug for plan file', max_length=100)),
                ('task_description', models.TextField(help_text='Original task description from user')),
                ('plan_content', models.TextField(help_text='Full markdown plan content')),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('ready', 'Ready for Approval'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='creating', help_text='Current plan status', max_length=20)),
                ('current_step_index', models.IntegerField(default=0, help_text='Index of currently executing step')),
                ('total_steps', models.IntegerField(default=0, help_text='Total number of steps in plan')),
                ('planning_job_id', models.CharField(blank=True, help_text='Coding agent job ID for planning phase', max_length=50)),
                ('implementation_job_id', models.CharField(blank=True, help_text='Coding agent job ID for implementation phase', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(help_text='Conversation this plan belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='agent_plans', to='conversations.conversation')),
            ],
            options={
                'verbose_name': 'Agent Plan',
                'verbose_name_plural': 'Agent Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClonedRepository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Full repository name: owner/repo', max_length=255)),
                ('clone_url', models.URLField(help_text='GitHub clone URL (https)')),
                ('default_branch', models.CharField(default='main', help_text='Default branch of the repository', max_length=100)),
                ('current_branch', models.CharField(default='main', help_text='Currently checked out branch', max_length=100)),
                ('workspace_path', models.CharField(help_text='Path to cloned repo in sandbox workspace', max_length=500)),
                ('head_commit_sha', models.CharField(blank=True, help_text='SHA of HEAD commit', max_length=40)),
                ('head_commit_message', models.CharField(blank=True, help_text='Message of HEAD commit', max_length=500)),
                ('cloned_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(help_text='Conversation that owns this cloned repository', on_delete=django.db.models.deletion.CASCADE, related_name='cloned_repository', to='conversations.conversation')),
            ],
            options={
                'verbose_name': 'Cloned Repository',
                'verbose_name_plural': 'Cloned Repositories',
            },
        ),
        migrations.CreateModel(
            name='CreatedPullRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pr_number', models.IntegerField(help_text='GitHub PR number')),
                ('pr_url', models.URLField(help_text='Full URL to the PR on GitHub')),
                ('pr_title', models.CharField(help_text='PR title', max_length=255)),
                ('head_branch', models.CharField(help_text='Branch containing changes (head)', max_length=100)),
                ('base_branch', models.CharField(help_text='Target branch for merge (base)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cloned_repo', models.ForeignKey(help_text='Repository this PR was created in', on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='code_sessions.clonedrepository')),
                ('plan', models.ForeignKey(blank=True, help_text='Plan that created this PR (may be null)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pull_requests', to='code_sessions.agentplan')),
            ],
            options={
                'verbose_name': 'Created Pull Request',
                'verbose_name_plural': 'Created Pull Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.IntegerField(help_text='Order of step in plan (1-indexed)')),
                ('title', models.CharField(help_text='Brief step title', max_length=255)),
                ('description', models.TextField(help_text='Detailed step description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current step status', max_length=20)),
                ('files_to_modify', models.JSONField(default=list, help_text='List of files planned to modify')),
                ('files_modified', models.JSONField(default=list, help_text='List of files actually modified')),
                ('result_summary', models.TextField(blank=True, help_text='Summary of what was done in this step')),
                ('plan', models.ForeignKey(help_text='Parent plan for this step', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='code_sessions.agentplan')),
            ],
            options={
                'verbose_name': 'Plan Step',
                'verbose_name_plural': 'Plan Steps',
                'ordering': ['plan', 'step_number'],
            },
        ),
        migrations.AddIndex(
            model_name='agentplan',
            index=models.Index(fields=['conversation', 'status'], name='code_sessio_convers_993602_idx'),
        ),
        migrations.AddIndex(
            model_name='agentplan',
            index=models.Index(fields=['conversation', '-created_at'], name='code_sessio_convers_e79de8_idx'),
        ),
        migrations.AddIndex(
            model_name='clonedrepository',
            index=models.Index(fields=['full_name'], name='code_sessio_full_na_b0e447_idx'),
        ),
        migrations.AddIndex(
            model_name='clonedrepository',
            index=models.Index(fields=['conversation'], name='code_sessio_convers_2c141d_idx'),
        ),
        migrations.AddIndex(
            model_name='createdpullrequest',
            index=models.Index(fields=['cloned_repo', '-created_at'], name='code_sessio_cloned__f054b2_idx'),
        ),
        migrations.AddIndex(
            model_name='createdpullrequest',
            index=models.Index(fields=['pr_number'], name='code_sessio_pr_numb_40d350_idx'),
        ),
        migrations.AddIndex(
            model_name='planstep',
            index=models.Index(fields=['plan', 'step_number'], name='code_sessio_plan_id_5ff249_idx'),
        ),
    ]
