# Generated by Django 5.1 on 2026-02-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_sessions', '0006_agentplan_clonedrepository_createdpullrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentplan',
            name='github_issue_number',
            field=models.IntegerField(blank=True, help_text='GitHub issue number this plan addresses', null=True),
        ),
        migrations.AddField(
            model_name='agentplan',
            name='github_issue_title',
            field=models.CharField(blank=True, help_text='Title of the GitHub issue', max_length=255),
        ),
        migrations.AddField(
            model_name='agentplan',
            name='github_issue_url',
            field=models.URLField(blank=True, help_text='Full URL to the GitHub issue'),
        ),
    ]
