# Generated by Django 5.1 on 2026-02-09 14:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_sessions', '0010_agentplan_chat_source_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Slug-safe agent name (used as filename)', max_length=100)),
                ('description', models.TextField(blank=True, help_text="Short description of the agent's purpose")),
                ('model_id', models.CharField(default='anthropic/claude-sonnet-4', help_text='OpenRouter model ID for this sub-agent', max_length=255)),
                ('system_prompt', models.TextField(blank=True, help_text='System prompt / instructions for the sub-agent', max_length=50000)),
                ('tools', models.JSONField(default=list, help_text='Allowed tools (e.g. Read, Glob, Grep)')),
                ('disallowed_tools', models.JSONField(default=list, help_text='Explicitly disallowed tools')),
                ('max_turns', models.IntegerField(default=10, help_text='Maximum agentic turns', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('permission_mode', models.CharField(choices=[('default', 'Default'), ('plan', 'Plan Only (Read-Only)'), ('autoEdit', 'Auto Edit'), ('fullAuto', 'Full Auto')], default='default', help_text='Permission mode for the sub-agent', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this agent is deployed to sandboxes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sub Agent',
                'verbose_name_plural': 'Sub Agents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='agentplan',
            new_name='code_sessio_chat_id_063c61_idx',
            old_name='code_sessio_chat_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='agentplan',
            new_name='code_sessio_chat_id_3c902c_idx',
            old_name='code_sessio_chat_id_repo_idx',
        ),
        migrations.AddField(
            model_name='subagent',
            name='user',
            field=models.ForeignKey(help_text='User who owns this sub-agent', on_delete=django.db.models.deletion.CASCADE, related_name='sub_agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='subagent',
            index=models.Index(fields=['user', 'is_active'], name='code_sessio_user_id_b8e10e_idx'),
        ),
        migrations.AddIndex(
            model_name='subagent',
            index=models.Index(fields=['user', '-updated_at'], name='code_sessio_user_id_52025e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subagent',
            unique_together={('user', 'name')},
        ),
    ]
