# Generated by Django 5.1 on 2026-02-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_sessions', '0012_usermodelpreferences_subagent_model_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subagent',
            name='model_tier',
            field=models.CharField(choices=[('fast', 'Fast'), ('balanced', 'Balanced'), ('powerful', 'Powerful'), ('inherit', 'Inherit from Chat')], default='inherit', help_text='Model tier for this sub-agent (fast/balanced/powerful/inherit)', max_length=20),
        ),
        migrations.AlterField(
            model_name='usermodelpreferences',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
