apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: sterna
  labels:
    app: frontend
    app.kubernetes.io/name: frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    app: frontend
