"""
Base settings for Sterna project.
"""

import os
from datetime import timedelta
from pathlib import Path
from typing import Any, Dict
import environ  # type: ignore[import-untyped]

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Initialize environment variables
env = environ.Env(DEBUG=(bool, False))

# Read .env file
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Environment
DJANGO_ENV = os.environ.get("DJANGO_ENV", "dev")

# Security
SECRET_KEY = env(
    "SECRET_KEY", default="django-insecure-development-key-change-this-in-production"
)

# Field-level encryption key for sensitive data (OAuth tokens, etc.)
# IMPORTANT: This key MUST be set in production and kept secret
# Generate with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# The development default below is public in this repository; prod.py
# refuses to boot with it (same fail-loud contract as SECRET_KEY).
DEV_FIELD_ENCRYPTION_KEY = "tqV8H-VqVlPBVQKvVR8mVJjKz5YQ7UVr_gJHZ4L9W2M="
FIELD_ENCRYPTION_KEY = env("FIELD_ENCRYPTION_KEY", default=DEV_FIELD_ENCRYPTION_KEY)

# BYOK (Bring-Your-Own-Key) encryption — separate setting from
# FIELD_ENCRYPTION_KEY so BYOK keys can be rotated independently of
# other encrypted user data (OAuth tokens, MCP creds). Defaults to
# FIELD_ENCRYPTION_KEY for backwards compatibility; in prod we point
# it at its own Scaleway Secret Manager entry.
BYOK_ENCRYPTION_KEY = env("BYOK_ENCRYPTION_KEY", default=FIELD_ENCRYPTION_KEY)

# Comma-separated list of legacy keys for MultiFernet rotation. Empty
# (default) means no legacy keys. Procedure: docs/operations/byok-key-rotation.md
BYOK_ENCRYPTION_KEY_LEGACY = env.list("BYOK_ENCRYPTION_KEY_LEGACY", default=[])

DEBUG = env("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1", "0.0.0.0"])

# Application definition
DJANGO_APPS = [
    "daphne",  # ASGI server, must be before staticfiles
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # Required for django-allauth
]

THIRD_PARTY_APPS = [
    "channels",  # Django Channels for WebSocket support
    "rest_framework",
    "corsheaders",
    "drf_spectacular",
    "django_celery_beat",  # Celery Beat scheduler
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "dj_rest_auth",
    "dj_rest_auth.registration",
]

LOCAL_APPS = [
    "authentication",
    "api",
    "llm",
    "mcp",  # Model Context Protocol integration
    "consigliere",  # AI advisor for model recommendations
    "audit_logging",
    "documentation",
    "voice_rooms",  # Multi-AI voice conversation rooms
    "code_sessions",  # Claude Code-like coding assistant
    "usage_quota",  # Centralized usage tracking and quota management
    "seed",  # Idempotent seed-data orchestrator (task 28)
    "workspaces",  # Sandbox workspace persistence
    "storage",  # R2 backup tasks + restore (task 22)
    "conversations",  # Conversation storage (PostgreSQL)
    "sparks",  # Interactive React components generated by AI
    "knowledge_base",  # User knowledge base with RAG
    "support",
    "notifications",  # Transactional email (Resend)
]
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",  # Required for django-allauth
    "sterna.middleware.request_id.RequestIDMiddleware",
    "audit_logging.middleware.AuditLoggingMiddleware",
]

ROOT_URLCONF = "sterna.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "sterna.wsgi.application"
ASGI_APPLICATION = "sterna.asgi.application"

# Database
# Prefer DATABASE_URL if set, otherwise use individual DB_* vars
DATABASE_URL = env("DATABASE_URL", default="")
if DATABASE_URL:
    import dj_database_url
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env("DB_NAME", default="sterna"),
            "USER": env("DB_USER", default="postgres"),
            "PASSWORD": env("DB_PASSWORD", default="postgres"),
            "HOST": env("DB_HOST", default="localhost"),
            "PORT": env("DB_PORT", default="5432"),
            "CONN_MAX_AGE": 600,
            "OPTIONS": {
                "connect_timeout": 10,
            },
        }
    }

# Redis configuration
# Prefer REDIS_URL if set, otherwise construct from individual vars
REDIS_URL = env("REDIS_URL", default="")
if not REDIS_URL:
    REDIS_HOST = env("REDIS_HOST", default="localhost")
    REDIS_PORT = env("REDIS_PORT", default="6379")
    REDIS_DB = env("REDIS_DB", default="0")
    REDIS_PASSWORD = env("REDIS_PASSWORD", default="")
    REDIS_URL = (
        f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
        if REDIS_PASSWORD
        else f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
    )
else:
    # Parse REDIS_URL for components needed by other configs
    from urllib.parse import urlparse
    _parsed = urlparse(REDIS_URL)
    REDIS_HOST = _parsed.hostname or "localhost"
    REDIS_PORT = str(_parsed.port or 6379)
    REDIS_DB = _parsed.path.lstrip("/") or "0"
    REDIS_PASSWORD = _parsed.password or ""

# Cache configuration
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
        "KEY_PREFIX": "sterna",
        "TIMEOUT": 300,
    }
}

# Django Channels layer (for WebSocket)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, int(REDIS_PORT))],
            "prefix": "sterna:channels:",
        },
    },
}

# Celery Configuration
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000

# Authentication
AUTH_USER_MODEL = "authentication.User"

AUTHENTICATION_BACKENDS = [
    "authentication.backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST Framework configuration
SPECTACULAR_SETTINGS = {
    'TITLE': 'Sterna API',
    'DESCRIPTION': 'Multi-model AI chat platform API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': '/api',
}

REST_FRAMEWORK: Dict[str, Any] = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "authentication.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.FormParser",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        # task-29 H1: CF-aware throttle subclasses (key by
        # CF-Connecting-IP, not REMOTE_ADDR).
        "sterna.throttling.AnonRateThrottle",
        "sterna.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
        "support_anon": "5/hour",
        "support_user": "10/day",
    },
    "DATETIME_FORMAT": "%Y-%m-%dT%H:%M:%S.%fZ",
    "DATE_FORMAT": "%Y-%m-%d",
    "TIME_FORMAT": "%H:%M:%S",
    "EXCEPTION_HANDLER": "sterna.exceptions.billing_exception_handler",
}

# CORS configuration
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    default=[
        "http://localhost:3000",
        "http://localhost:5173",
        "http://127.0.0.1:3000",
        "http://127.0.0.1:5173",
    ],
)
CORS_ALLOW_CREDENTIALS = True

# Logging configuration.
# Console-only, via the same shared helper settings.prod/staging/test
# use (see sterna/logging.py) — settings.dev (the common case, since
# base.py is what dev.py inherits) picks env="dev" for human-readable
# output; settings.prod/test replace this with their own env after
# `from .base import *`. Deliberately no file handler: a
# RotatingFileHandler here previously wrote to
# BASE_DIR/logs/django.log, a gitignored directory that doesn't exist
# on a fresh clone — the "web" container bind-mounts the repo over
# /app, shadowing the image's own `mkdir -p logs` step, so Django
# crash-looped with FileNotFoundError at import time. Every deployed
# environment already logs to stdout only (container log driver /
# `kubectl logs` handle collection); reintroduce file logging only via
# an explicit, directory-creating opt-in if ever needed.
from sterna.logging import build_logging_config  # noqa: E402

LOGGING = build_logging_config(env="dev", service="web")

# Security settings
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = "DENY"
SECURE_CONTENT_TYPE_NOSNIFF = True

# Session configuration
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False  # Set to True in production
SESSION_COOKIE_SAMESITE = "Lax"

# S3 configuration (optional - for external integrations)
AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID", default="")
AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY", default="")
AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME", default="")
AWS_S3_REGION_NAME = env("AWS_S3_REGION_NAME", default="us-east-1")
AWS_S3_CUSTOM_DOMAIN = env("AWS_S3_CUSTOM_DOMAIN", default="")
AWS_DEFAULT_ACL = None
AWS_S3_OBJECT_PARAMETERS = {
    "CacheControl": "max-age=86400",
}

# Per-environment marker. Used to synthesize names like
# sternaway-backups-<env>. Defined here (above the R2 block) so the
# R2 backup dest-bucket default references the same constant the rest
# of the codebase uses; the "development" default deliberately does
# not match any real bucket, so a misconfigured pod fails loudly
# rather than writing prod data into the staging bucket.
ENVIRONMENT = env("ENVIRONMENT", default="development")

# Stripe billing (task 11). STRIPE_API_KEY is sk_test_… in dev/staging,
# sk_live_… in prod. STRIPE_LIVE_MODE is a derived flag used by
# sanity_check_stripe_mode to refuse cross-env key drift.
STRIPE_API_KEY = env("STRIPE_API_KEY", default="")
STRIPE_PUBLISHABLE_KEY = env("STRIPE_PUBLISHABLE_KEY", default="")
STRIPE_WEBHOOK_SECRET = env("STRIPE_WEBHOOK_SECRET", default="")
STRIPE_LIVE_MODE = STRIPE_API_KEY.startswith("sk_live_")

# Cloudflare R2 Storage (for workspace file persistence)
# R2 is S3-compatible, so we use similar config pattern
R2_ACCOUNT_ID = env("R2_ACCOUNT_ID", default="")
R2_ACCESS_KEY_ID = env("R2_ACCESS_KEY_ID", default="")
R2_SECRET_ACCESS_KEY = env("R2_SECRET_ACCESS_KEY", default="")
R2_BUCKET_NAME = env("R2_BUCKET_NAME", default="sterna-workspaces")
# For local dev, can point to MinIO instead of R2
R2_ENDPOINT_URL = env("R2_ENDPOINT_URL", default="")

# R2 backup configuration (task 22)
# Buckets to back up. Default: only the user-assets bucket.
R2_BACKUP_SOURCE_BUCKETS = env.list(
    "R2_BACKUP_SOURCE_BUCKETS", default=[R2_BUCKET_NAME]
)
# Destination bucket holds DB and R2 backups under disjoint prefixes
# (DB at "<env>/", R2 at "r2/"). ENVIRONMENT must be set per cluster
# via common-config; the "development" fallback is intentionally not
# a real bucket so misconfiguration is loud.
R2_BACKUP_DEST_BUCKET = env(
    "R2_BACKUP_DEST_BUCKET",
    default=f"sternaway-backups-{ENVIRONMENT}",
)
# Per-object size cap; we skip-and-warn anything bigger to avoid
# multipart-copy bookkeeping.
R2_BACKUP_MAX_OBJECT_BYTES = env.int(
    "R2_BACKUP_MAX_OBJECT_BYTES", default=5 * 1024 * 1024 * 1024
)
# Per-run failure tolerance (absolute count + ratio).
R2_BACKUP_PER_RUN_TOLERANCE = env.int(
    "R2_BACKUP_PER_RUN_TOLERANCE", default=5
)
R2_BACKUP_PER_RUN_FAILURE_RATIO = env.float(
    "R2_BACKUP_PER_RUN_FAILURE_RATIO", default=0.01
)
# Below this many total attempts in a single run, the ratio cap is
# skipped (small-bucket false-positive guard — see plan §0.6).
R2_BACKUP_RATIO_FLOOR = env.int(
    "R2_BACKUP_RATIO_FLOOR", default=200
)

# Workspace sync configuration
# Files smaller than this are stored inline in PostgreSQL
WORKSPACE_INLINE_THRESHOLD = env.int("WORKSPACE_INLINE_THRESHOLD", default=256 * 1024)  # 256KB
# Maximum file size to sync
WORKSPACE_MAX_FILE_SIZE = env.int("WORKSPACE_MAX_FILE_SIZE", default=50 * 1024 * 1024)  # 50MB
# Maximum total workspace size
WORKSPACE_MAX_SIZE = env.int("WORKSPACE_MAX_SIZE", default=500 * 1024 * 1024)  # 500MB

# Internal Service Authentication
# Token for orchestrator → Django backend communication
# Generate with: python -c "import secrets; print(secrets.token_urlsafe(32))"
INTERNAL_SERVICE_TOKEN = env("INTERNAL_SERVICE_TOKEN", default="")

# JWT Configuration
JWT_SECRET_KEY = env("JWT_SECRET_KEY", default=SECRET_KEY)
JWT_ALGORITHM = "HS256"
JWT_ACCESS_TOKEN_LIFETIME = timedelta(minutes=15)
JWT_REFRESH_TOKEN_LIFETIME = timedelta(days=7)
JWT_AUTH_HEADER_PREFIX = "Bearer"
# Refresh-token rotation reuse-grace window: a just-rotated refresh
# token may rotate again within this window (concurrent-request race
# from parallel 401 retries — the frontend has no single-flight
# refresh mutex) instead of triggering family-wide revocation.
JWT_REFRESH_ROTATION_GRACE = timedelta(
    seconds=env.int("JWT_REFRESH_ROTATION_GRACE_SECONDS", default=60)
)

# OpenRouter configuration
OPENROUTER_API_KEY = env("OPENROUTER_API_KEY", default="")
OPENROUTER_API_BASE = env("OPENROUTER_API_BASE", default="https://openrouter.ai/api/v1")
OPENROUTER_DEFAULT_MODEL = env(
    "OPENROUTER_DEFAULT_MODEL", default="openai/gpt-4-turbo-preview"
)

# OpenRouter Provisioning API (for per-user keys)
# Create at: https://openrouter.ai/settings/provisioning-keys
OPENROUTER_PROVISIONING_KEY = env("OPENROUTER_PROVISIONING_KEY", default="")
# Default credit limit for new users (USD) - high backstop, real limits from usage service
OPENROUTER_DEFAULT_USER_LIMIT = env.float("OPENROUTER_DEFAULT_USER_LIMIT", default=100.0)
# Limit reset frequency: daily, weekly, monthly, or empty for no reset
OPENROUTER_LIMIT_RESET = env("OPENROUTER_LIMIT_RESET", default="weekly")

# Image Generation configuration
# Fallback chain: Google AI Studio (free) → OpenRouter (fallback)
GOOGLE_AI_STUDIO_API_KEY = env("GOOGLE_AI_STUDIO_API_KEY", default="")
# Note: OPENROUTER_API_KEY is already defined above and reused for image generation fallback

# Support notifications
SUPPORT_SLACK_WEBHOOK_URL = env("SUPPORT_SLACK_WEBHOOK_URL", default="")

# GitHub App configuration
GITHUB_APP_ID = env("GITHUB_APP_ID", default="")
GITHUB_PRIVATE_KEY = env("GITHUB_PRIVATE_KEY", default="")
GITHUB_WEBHOOK_SECRET = env("GITHUB_WEBHOOK_SECRET", default="")

# Performance Monitoring Settings
PROMETHEUS_METRICS_PORT = int(env("PROMETHEUS_METRICS_PORT", default="9090"))
# ENVIRONMENT is defined above (near the R2 block) so it is in scope
# for R2_BACKUP_DEST_BUCKET synthesis.

# OpenTelemetry Settings
OTEL_SERVICE_NAME = env("OTEL_SERVICE_NAME", default="sterna-ai")
OTEL_SERVICE_VERSION = env("OTEL_SERVICE_VERSION", default="1.0.0")
OTEL_EXPORTER_OTLP_ENDPOINT = env("OTEL_EXPORTER_OTLP_ENDPOINT", default="")

# Django Sites Framework
SITE_ID = 1

# Django-Allauth Configuration
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_REQUIRED = False

# Social Account Providers
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': env('GOOGLE_OAUTH_CLIENT_ID', default=''),
            'secret': env('GOOGLE_OAUTH_CLIENT_SECRET', default=''),
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
            'prompt': 'select_account',
        },
        'VERIFIED_EMAIL': True,
    }
}

# Google OAuth Configuration
GOOGLE_OAUTH_CLIENT_ID = env('GOOGLE_OAUTH_CLIENT_ID', default='')
GOOGLE_OAUTH_CLIENT_SECRET = env('GOOGLE_OAUTH_CLIENT_SECRET', default='')

# GitHub OAuth Configuration (shared for authentication + MCP connector)
# Uses same GitHub OAuth app for both flows, differentiated by state parameter:
# - Authentication flow: normal state
# - MCP connector flow: state prefixed with "mcp:"
GITHUB_OAUTH_CLIENT_ID = env('GITHUB_OAUTH_CLIENT_ID', default='')
GITHUB_OAUTH_CLIENT_SECRET = env('GITHUB_OAUTH_CLIENT_SECRET', default='')
GITHUB_OAUTH_REDIRECT_URI = env('GITHUB_OAUTH_REDIRECT_URI', default='http://localhost:5173/oauth/callback')

# MCP Connector OAuth Configurations
# Notion
NOTION_OAUTH_CLIENT_ID = env('NOTION_OAUTH_CLIENT_ID', default='')
NOTION_OAUTH_CLIENT_SECRET = env('NOTION_OAUTH_CLIENT_SECRET', default='')
NOTION_OAUTH_REDIRECT_URI = env('NOTION_OAUTH_REDIRECT_URI', default='http://localhost:5173/oauth/callback')

# Slack
SLACK_OAUTH_CLIENT_ID = env('SLACK_OAUTH_CLIENT_ID', default='')
SLACK_OAUTH_CLIENT_SECRET = env('SLACK_OAUTH_CLIENT_SECRET', default='')
SLACK_OAUTH_REDIRECT_URI = env('SLACK_OAUTH_REDIRECT_URI', default='http://localhost:5173/oauth/callback')

# Atlassian (Jira/Confluence)
ATLASSIAN_OAUTH_CLIENT_ID = env('ATLASSIAN_OAUTH_CLIENT_ID', default='')
ATLASSIAN_OAUTH_CLIENT_SECRET = env('ATLASSIAN_OAUTH_CLIENT_SECRET', default='')
ATLASSIAN_OAUTH_REDIRECT_URI = env('ATLASSIAN_OAUTH_REDIRECT_URI', default='http://localhost:5173/oauth/callback')

# dj-rest-auth Configuration
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_HTTPONLY': False,
    'TOKEN_MODEL': None,  # We're using JWT, not token authentication
}

# Frontend URL for redirects
FRONTEND_URL = env('FRONTEND_URL', default='http://localhost:5173')

# Transactional email (Task 3)
BRAND_NAME = env('BRAND_NAME', default='Sterna')
SUPPORT_EMAIL = env('SUPPORT_EMAIL', default='support@example.com')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='noreply@example.com')

# Backend URL for OAuth callbacks (MCP connectors)
SITE_URL = env('SITE_URL', default='http://localhost:8000')

# Public site URL sent as the OpenRouter attribution header (HTTP-Referer /
# X-Title). Neutral default so a fresh deployment doesn't advertise someone
# else's domain; override with the real public URL in production.
OPENROUTER_SITE_URL = env('OPENROUTER_SITE_URL', default='https://example.com')

# Allow OAuth redirect URIs
if DEBUG:
    # Development OAuth redirect URIs
    ALLOWED_REDIRECT_URIS = [
        'http://localhost:5173',
        'http://localhost:8000',
        'http://127.0.0.1:5173',
        'http://127.0.0.1:8000',
    ]

# Skills Marketplace
# Comma-separated list of "label|url" marketplace sources
SKILL_MARKETPLACE_SOURCES = env(
    'SKILL_MARKETPLACE_SOURCES',
    default='Anthropic|https://github.com/anthropics/skills,Engineering & Docs|https://github.com/mhattingpete/claude-skills-marketplace,65 Skills Collection|https://github.com/alirezarezvani/claude-skills',
)

# Sandbox Configuration
# URLs for sandbox microservices
ORCHESTRATOR_URL = env('ORCHESTRATOR_URL', default='http://orchestrator:8003')

# Voice Rooms Configuration
# Deepgram STT (Speech-to-Text)
DEEPGRAM_API_KEY = env('DEEPGRAM_API_KEY', default='')
DEEPGRAM_MODEL = env('DEEPGRAM_MODEL', default='nova-2')
DEEPGRAM_PUNCTUATE = env.bool('DEEPGRAM_PUNCTUATE', default=True)
DEEPGRAM_INTERIM_RESULTS = env.bool('DEEPGRAM_INTERIM_RESULTS', default=True)
DEEPGRAM_ENDPOINTING_MS = env.int('DEEPGRAM_ENDPOINTING_MS', default=500)
DEEPGRAM_UTTERANCE_END_MS = env.int('DEEPGRAM_UTTERANCE_END_MS', default=1500)

# OpenAI TTS (Text-to-Speech) and Video Generation (Sora)
# Models: tts-1 (standard), tts-1-hd (high quality)
# Voices: alloy, echo, fable, onyx, nova, shimmer
OPENAI_API_KEY = env('OPENAI_API_KEY', default='')

# Runway Video Generation (Veo, Gen-4, Act Two, Upscale)
# Get your key at: https://dev.runwayml.com/
RUNWAY_API_KEY = env('RUNWAY_API_KEY', default='')

# ElevenLabs TTS (Text-to-Speech)
# Models: eleven_multilingual_v2 (highest quality), eleven_turbo_v2_5 (good quality + low latency), eleven_flash_v2_5 (fastest)
ELEVENLABS_API_KEY = env('ELEVENLABS_API_KEY', default='')
# TTS Model: eleven_flash_v2_5 (fastest, recommended for WebSocket), eleven_turbo_v2_5 (balanced), eleven_multilingual_v2 (highest quality)
# Note: eleven_v3 does NOT support WebSocket streaming
ELEVENLABS_MODEL = env('ELEVENLABS_MODEL', default='eleven_flash_v2_5')
ELEVENLABS_OPTIMIZE_LATENCY = env.int('ELEVENLABS_OPTIMIZE_LATENCY', default=2)  # 0=best quality, 4=lowest latency
# Stability: 'creative' (0.3), 'natural' (0.5), 'robust' (0.7) - v3 is more sensitive to this
ELEVENLABS_STABILITY = env.float('ELEVENLABS_STABILITY', default=0.5)  # 'natural' - balanced for v3
ELEVENLABS_SIMILARITY_BOOST = env.float('ELEVENLABS_SIMILARITY_BOOST', default=0.8)
ELEVENLABS_STYLE = env.float('ELEVENLABS_STYLE', default=0.3)  # 0-1, higher = more expressive/emotional
ELEVENLABS_USE_SPEAKER_BOOST = env.bool('ELEVENLABS_USE_SPEAKER_BOOST', default=True)
# V3-specific: List of models that support audio tags like [laughs], [sighs], [whispers]
# Note: These models do NOT support WebSocket streaming (REST API only)
ELEVENLABS_V3_MODELS = ['eleven_v3', 'eleven_v3_flash']

# Voice Room Audio Settings
AUDIO_SAMPLE_RATE = env.int('AUDIO_SAMPLE_RATE', default=16000)
AUDIO_CHANNELS = env.int('AUDIO_CHANNELS', default=1)
DEFAULT_MAX_TOKENS = env.int('DEFAULT_MAX_TOKENS', default=500)
MAX_AGENTS_PER_ROOM = env.int('MAX_AGENTS_PER_ROOM', default=5)

# Knowledge Base / RAG Configuration
KNOWLEDGE_BASE_EMBEDDING_MODEL = env('KNOWLEDGE_BASE_EMBEDDING_MODEL', default='openai/text-embedding-3-large')
KNOWLEDGE_BASE_EMBEDDING_DIMENSIONS = env.int('KNOWLEDGE_BASE_EMBEDDING_DIMENSIONS', default=1536)
KNOWLEDGE_BASE_EMBEDDING_API_URL = env('KNOWLEDGE_BASE_EMBEDDING_API_URL', default='https://openrouter.ai/api/v1/embeddings')
KNOWLEDGE_BASE_CHUNK_SIZE = env.int('KNOWLEDGE_BASE_CHUNK_SIZE', default=500)
KNOWLEDGE_BASE_CHUNK_OVERLAP = env.int('KNOWLEDGE_BASE_CHUNK_OVERLAP', default=50)
KNOWLEDGE_BASE_INLINE_THRESHOLD = env.int('KNOWLEDGE_BASE_INLINE_THRESHOLD', default=256 * 1024)  # 256KB
KNOWLEDGE_BASE_R2_BUCKET = env('KNOWLEDGE_BASE_R2_BUCKET', default='sternaway-knowledge')
KNOWLEDGE_BASE_DEFAULT_STORAGE_MB = env.int('KNOWLEDGE_BASE_DEFAULT_STORAGE_MB', default=100)
KNOWLEDGE_BASE_DEFAULT_SIMILARITY_THRESHOLD = env.float('KNOWLEDGE_BASE_DEFAULT_SIMILARITY_THRESHOLD', default=0.7)
KNOWLEDGE_BASE_DEFAULT_MAX_CHUNKS = env.int('KNOWLEDGE_BASE_DEFAULT_MAX_CHUNKS', default=5)
KNOWLEDGE_BASE_MAX_CONTEXT_TOKENS = env.int('KNOWLEDGE_BASE_MAX_CONTEXT_TOKENS', default=2000)

# Smart Router Configuration (intelligent model routing engine)
SMART_ROUTER_ROUTING_POOL = [
    {"model_id": "google/gemini-2.0-flash-001", "cost_tier": "budget", "min": 0, "max": 30, "priority": 10},
    {"model_id": "google/gemini-2.5-flash-lite", "cost_tier": "budget", "min": 0, "max": 40, "priority": 5},
    {"model_id": "anthropic/claude-haiku-4.5", "cost_tier": "balanced", "min": 15, "max": 65, "priority": 10},
    {"model_id": "anthropic/claude-sonnet-4.5", "cost_tier": "premium", "min": 40, "max": 100, "priority": 10},
]

# Signup abuse prevention (task 19)
# Operations escape hatch: comma-separated EMAIL ADDRESSES (not domains)
# allowed even if the domain is on the disposable-email blocklist.
DISPOSABLE_EMAIL_ALLOWLIST = env.list("DISPOSABLE_EMAIL_ALLOWLIST", default=[])

# Cloudflare Turnstile (CAPTCHA) — task 19
# Public site key is rendered in the frontend via VITE_TURNSTILE_SITE_KEY.
# Secret key is used by core/authentication/services/turnstile.py for
# server-side verification. In DEBUG=True or when the secret is empty,
# verification is bypassed (dev/test ergonomics).
TURNSTILE_SITE_KEY = env("TURNSTILE_SITE_KEY", default="")
TURNSTILE_SECRET_KEY = env("TURNSTILE_SECRET_KEY", default="")

# task-29 C3: hosts allowed as targets for the non-r2:// avatar redirect
# in core/authentication/views.py:serve_user_avatar. Suffix-matched.
AVATAR_REDIRECT_ALLOWLIST = env.list(
    "AVATAR_REDIRECT_ALLOWLIST",
    default=["googleusercontent.com", "avatars.githubusercontent.com"],
)

# task-29 H1: when True, ``get_client_ip`` requires CF-Connecting-IP
# and emits a suspicious-activity event if it's missing (fail-open
# fallback to XFF/REMOTE_ADDR so direct-to-pod healthchecks don't
# break). Staging/prod override to True; dev/test stay False.
CF_REQUIRE_HEADER = env.bool("CF_REQUIRE_HEADER", default=False)

# task-29 H4: explicit opt-in for the dev-token JWT bypass. ``DEBUG``
# alone is not enough — production deploys with ``DJANGO_ENV=prod``
# must hard-reject dev tokens even if DEBUG is accidentally on.
DEV_TOKEN_BYPASS = env.bool("DEV_TOKEN_BYPASS", default=False)
