apiVersion: v1
kind: Service
metadata:
  name: brave-search
  namespace: sterna
  labels:
    app: brave-search
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8004
  selector:
    app: brave-search
