# Generated by Django 5.1 on 2026-02-01 13:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogRetentionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('retention_value', models.PositiveIntegerField(help_text='How long to keep audit logs')),
                ('retention_unit', models.CharField(choices=[('days', 'Days'), ('months', 'Months'), ('years', 'Years')], default='days', max_length=10)),
                ('action_category', models.CharField(blank=True, choices=[('AUTH', 'Authentication'), ('PROJECT', 'Project Management'), ('DATASET', 'Dataset Operations'), ('EVALUATION', 'Evaluations'), ('RUBRIC', 'Rubrics'), ('USER', 'User Management'), ('PERMISSION', 'Permissions'), ('SYSTEM', 'System Operations'), ('API', 'API Access'), ('EXPORT', 'Data Export'), ('IMPORT', 'Data Import'), ('CONFIG', 'Configuration')], help_text='Apply to specific category, or null for all', max_length=20, null=True)),
                ('archive_before_deletion', models.BooleanField(default=True, help_text='Archive logs to cold storage before deletion')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audit Log Retention Policy',
                'verbose_name_plural': 'Audit Log Retention Policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('action_category', models.CharField(blank=True, choices=[('AUTH', 'Authentication'), ('PROJECT', 'Project Management'), ('DATASET', 'Dataset Operations'), ('EVALUATION', 'Evaluations'), ('RUBRIC', 'Rubrics'), ('USER', 'User Management'), ('PERMISSION', 'Permissions'), ('SYSTEM', 'System Operations'), ('API', 'API Access'), ('EXPORT', 'Data Export'), ('IMPORT', 'Data Import'), ('CONFIG', 'Configuration')], db_index=True, max_length=20, null=True)),
                ('resource_id', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_str', models.CharField(blank=True, help_text='String representation of the resource at time of action', max_length=255, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, help_text='Request ID for correlation', max_length=100, null=True)),
                ('session_id', models.CharField(blank=True, help_text='Session ID for grouping related actions', max_length=100, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Duration of the action in milliseconds', null=True)),
                ('resource_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_loggi_timesta_ed01f6_idx'), models.Index(fields=['user', '-timestamp'], name='audit_loggi_user_id_1a649b_idx'), models.Index(fields=['action', '-timestamp'], name='audit_loggi_action_058275_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_loggi_resourc_72ccbc_idx'), models.Index(fields=['action_category', '-timestamp'], name='audit_loggi_action__db7303_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLogArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_id', models.UUIDField(db_index=True)),
                ('archived_data', models.JSONField()),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('storage_location', models.CharField(blank=True, help_text='S3 key or other storage location', max_length=500, null=True)),
                ('archived_by_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit_logging.auditlogretentionpolicy')),
            ],
            options={
                'verbose_name': 'Audit Log Archive',
                'verbose_name_plural': 'Audit Log Archives',
                'ordering': ['-archived_at'],
                'indexes': [models.Index(fields=['original_id'], name='audit_loggi_origina_6aaecc_idx'), models.Index(fields=['-archived_at'], name='audit_loggi_archive_08d65b_idx')],
            },
        ),
    ]
