# Generated by Django 5.1 on 2025-12-25 18:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('weekly_limit_usd', models.DecimalField(decimal_places=2, help_text='Rolling 7-day spending limit in USD', max_digits=10)),
                ('session_limit_usd', models.DecimalField(decimal_places=2, help_text='Per-session spending limit in USD', max_digits=10)),
                ('features', models.JSONField(default=dict, help_text="Feature access flags, e.g., {'voice_rooms': true, 'code_sessions': true}")),
                ('chat_weekly_limit_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Optional per-feature weekly limit for chat', max_digits=10, null=True)),
                ('voice_room_weekly_limit_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Optional per-feature weekly limit for voice rooms', max_digits=10, null=True)),
                ('code_session_weekly_limit_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Optional per-feature weekly limit for code sessions', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='If true, new users are assigned this plan by default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['weekly_limit_usd'],
            },
        ),
        migrations.CreateModel(
            name='ServicePricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('openrouter', 'OpenRouter LLM'), ('elevenlabs_tts', 'ElevenLabs TTS'), ('openai_tts', 'OpenAI TTS'), ('deepgram_stt', 'Deepgram STT'), ('brave_search', 'Brave Search')], db_index=True, max_length=50)),
                ('model_id', models.CharField(blank=True, db_index=True, help_text='Specific model identifier (blank for service-wide default)', max_length=255)),
                ('price_per_1m_input_tokens', models.DecimalField(blank=True, decimal_places=6, help_text='Price per 1M input/prompt tokens (for LLM services)', max_digits=12, null=True)),
                ('price_per_1m_output_tokens', models.DecimalField(blank=True, decimal_places=6, help_text='Price per 1M output/completion tokens (for LLM services)', max_digits=12, null=True)),
                ('price_per_1k_chars', models.DecimalField(blank=True, decimal_places=6, help_text='Price per 1K characters (for TTS services)', max_digits=10, null=True)),
                ('price_per_minute', models.DecimalField(blank=True, decimal_places=6, help_text='Price per audio minute (for STT services)', max_digits=10, null=True)),
                ('price_per_request', models.DecimalField(blank=True, decimal_places=6, help_text='Price per request (for search services)', max_digits=10, null=True)),
                ('effective_from', models.DateTimeField(db_index=True)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service Pricing',
                'verbose_name_plural': 'Service Pricing',
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['service', 'model_id', 'effective_from'], name='usage_quota_service_7be213_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_weekly_limit_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Override weekly limit (if set, takes precedence over plan)', max_digits=10, null=True)),
                ('custom_session_limit_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Override session limit (if set, takes precedence over plan)', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='usage_quota.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('openrouter', 'OpenRouter LLM'), ('elevenlabs_tts', 'ElevenLabs TTS'), ('openai_tts', 'OpenAI TTS'), ('deepgram_stt', 'Deepgram STT'), ('brave_search', 'Brave Search')], db_index=True, max_length=50)),
                ('feature', models.CharField(choices=[('chat', 'Chat'), ('voice_room', 'Voice Room'), ('code_session', 'Code Session'), ('search', 'Search'), ('consigliere', 'Consigliere'), ('other', 'Other')], db_index=True, help_text='Which feature triggered this usage', max_length=50)),
                ('session_id', models.CharField(blank=True, db_index=True, help_text='Session ID for grouping related usage (e.g., voice room session)', max_length=255)),
                ('model_id', models.CharField(blank=True, max_length=255)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('character_count', models.IntegerField(default=0)),
                ('audio_seconds', models.FloatField(default=0)),
                ('request_count', models.IntegerField(default=1)),
                ('cost_usd', models.DecimalField(decimal_places=6, help_text='Cost in USD', max_digits=10)),
                ('request_id', models.CharField(blank=True, help_text='External request ID (e.g., OpenRouter request ID)', max_length=255)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional service-specific metadata')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usage Log',
                'verbose_name_plural': 'Usage Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='usage_quota_user_id_e86985_idx'), models.Index(fields=['user', 'service', 'timestamp'], name='usage_quota_user_id_3ba17a_idx'), models.Index(fields=['user', 'feature', 'timestamp'], name='usage_quota_user_id_80d295_idx'), models.Index(fields=['session_id', 'timestamp'], name='usage_quota_session_4ac6db_idx')],
            },
        ),
    ]
