# Generated by Django 5.1 on 2025-12-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage_quota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='session_window_start',
            field=models.DateTimeField(blank=True, help_text='Start of current session window (3h). Null = no active session.', null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='weekly_window_start',
            field=models.DateTimeField(blank=True, help_text='Start of current weekly window (7d). Null = no active window.', null=True),
        ),
    ]
