# Generated by Django 5.1 on 2026-07-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage_quota', '0012_usersubscription_stripe_event_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='weekly_limit_usd',
            field=models.DecimalField(decimal_places=2, help_text='Fixed 7-day spending limit in USD (starts on first usage)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='billing_origin',
            field=models.CharField(choices=[('platform', 'Platform'), ('byok', 'BYOK')], db_index=True, default='platform', help_text="Who pays for this usage: 'platform' (Sterna) or 'byok' (user-uploaded OpenRouter key).", max_length=16),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='feature',
            field=models.CharField(choices=[('chat', 'Chat'), ('voice_room', 'Voice Room'), ('code_session', 'Code Session'), ('search', 'Search'), ('consigliere', 'Consigliere'), ('knowledge_base', 'Knowledge Base'), ('other', 'Other')], db_index=True, help_text='Which feature triggered this usage', max_length=50),
        ),
    ]
