apiVersion: v1
kind: Service
metadata:
  name: egress-proxy
  namespace: sterna
  labels:
    app: egress-proxy
    app.kubernetes.io/name: egress-proxy
spec:
  type: ClusterIP
  ports:
    - name: http-proxy
      port: 8888
      targetPort: http-proxy
      protocol: TCP
    - name: control
      port: 8889
      targetPort: control
      protocol: TCP
  selector:
    app: egress-proxy
