apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: sterna
  labels:
    app: web
    app.kubernetes.io/name: web
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app: web
