/**
 * Sparks Types
 *
 * Type definitions for Sparks (interactive React components generated by AI).
 * The store has been moved to artifactsPanelStore.ts.
 */

import type { SparkAsset } from '@/components/models/SparkRenderer'

interface SparkLatestDeployment {
  id: string
  status: string
  preview_url: string
  claim_url: string
}

export interface SparkDefinition {
  id: string
  title: string
  framework: 'react' | 'html' | 'svg' | 'markdown' | 'mermaid' | 'pdf' | 'docx' | 'ics' | 'csv' | 'xlsx'
  code: string
  version?: number
  parent_id?: string | null  // ID of the parent spark (for version tracking)
  assets?: SparkAsset[]  // Assets available via window.__SPARK_ASSETS__
  dependencies?: string[]  // npm packages used by the spark
  download_url?: string | null  // For downloadable types (csv/ics/pdf/docx)
  latest_deployment?: SparkLatestDeployment | null
  is_ignited?: boolean
}
