"""Translation of API chat messages into LangChain message objects.

Adapter. Only the LangChain streaming path needs it; the Direct Client
path speaks the OpenAI wire format natively.
"""

import logging
from typing import Any, Dict, List

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage

# Child of the configured "llm" logger (see sterna/logging.py APP_LOGGERS).
logger = logging.getLogger(__name__)

ROLE_USER = "user"
ROLE_ASSISTANT = "assistant"
ROLE_SYSTEM = "system"

CONTENT_PART_TEXT = "text"
CONTENT_PART_IMAGE_URL = "image_url"

_MESSAGE_CLASS_BY_ROLE = {
    ROLE_USER: HumanMessage,
    ROLE_ASSISTANT: AIMessage,
    ROLE_SYSTEM: SystemMessage,
}


def normalize_content(content):
    """Flatten a text-only content-part list; keep multimodal lists intact."""
    if not isinstance(content, list):
        return content

    has_images = any(part.get("type") == CONTENT_PART_IMAGE_URL for part in content)
    if has_images:
        # Keep multimodal content structure for vision models:
        # LangChain HumanMessage accepts a list of content parts.
        logger.info(f"[LangChain] Processing multimodal message with {len(content)} parts")
        return content

    text_parts = [
        part.get("text", "") for part in content if part.get("type") == CONTENT_PART_TEXT
    ]
    return " ".join(text_parts)


def convert_messages(messages: List[Dict[str, Any]]) -> List:
    """
    Convert API messages to LangChain message objects.

    Tool messages in the input are skipped -- they are regenerated by the
    tool loop.
    """
    lc_messages = []

    for msg in messages:
        if msg is None:
            continue

        # Normalized before the role check so the multimodal diagnostic
        # fires for every message, exactly as it did inline.
        content = normalize_content(msg.get("content", ""))

        message_class = _MESSAGE_CLASS_BY_ROLE.get(msg.get("role", ""))
        if message_class is None:
            continue

        lc_messages.append(message_class(content=content))

    return lc_messages
